document.addEventListener("DOMContentLoaded", function() {
    const galleryData = [
{"Type": "Engagement", "Images": "https://v5.airtableusercontent.com/v3/u/29/29/1718128800000/ZvUDh268ftGHLWCLsNdrvA/bGL-yxhX4tX6Jaw_dTjbNRtcQNn-BRCKjxKwiFBNmIAc_6CsKvmAiTWISrb97lfDHvYDxpQ1Gg0b8kmKF26t7kSNYcXskf7ycxPgu7b4OhT-rFOVbQ2xzXqn_hp1sD0_Zus5Jr8cO9y1zAPKa4TZNQw5DW_qOqviqBmxLOHdyko/CLfb4NBl4Y0miPnDWZdG3twBGpZuFyJF0XWqRAvVUco", "Materials": "Platinum, Diamond, Accent Stones, Prong Setting, Cluster, Shank Set, Engagement Ring", "Description": "This ladies' platinum ring features a pear cut diamond along with marquise cut accent diamonds.", "Designer": "Robert Corio Designs", "Name": "", "Keywords": ""},
{"Type": "Engagement", "Images": "https://v5.airtableusercontent.com/v3/u/29/29/1718128800000/zRY_P3dlJF1DX5kO3U_Fbw/DHwdtno387kk1Wr8faIlcPD_4HIVVr3YLbO6YOOEXBjNNEBX91jI5yKJnoPlQNC1JqmeTEL1rE7v2OjI6NfEhwXY2LE1CiwGuchMP4D7oQ2Vb6hpY_rq1_s6drrumuubOyg4Ef29gZRvS8L_5oqo9q35ilpuNSqjOI_JgjYMmEc/7N2eVJw6TZqspCTGo3c44_wa_KO4hRA1yMxy2Yrh7Bs", "Materials": "Platinum, Diamond, Halo, Shared Prongs, Accent Stones, Prong Setting, Engagement Ring", "Description": "This platinum engagement ring features a 1.22ct main diamond along with a fourteen 1.8mm diamond halo.", "Designer": "Robert Corio Designs", "Name": "", "Keywords": ""},
{"Type": "Engagement", "Images": "https://v5.airtableusercontent.com/v3/u/29/29/1718128800000/zQLTtGO2iDTslh4-tOrkEg/LWtbi1u1_pE3fPKWD-deqLvo7EZ7OEBnQFGSa9SZbvS14QROUjYWIFd68TaB1b_OT3iWcYweAKtW3X53lokyZyFotoh8RtukGhM1uBY0mKV457HeGs42rMiP5MfkEtJ2EYkEBgCv96C8nAXWlU3zFQ/ewFqX3Lw9CBNzDRri_RoUwMcO5_FCUvIVQKythGhnnc", "Materials": "Platinum, Diamond, Cushion Diamond, Accent stones, Channel setting, Shared Prongs, Prong Setting, Engagement Ring", "Description": "This platinum ring features a 1.5ct GIA certified Diamond surrounded by diamonds ranging from 2.8mm-2.1mm.", "Designer": "Robert Corio Designs", "Name": "", "Keywords": ""},
{"Type": "Engagement", "Images": "https://v5.airtableusercontent.com/v3/u/29/29/1718128800000/xTTJsrY8HCZreAa8_Geohg/oxIaILkiXD0aGL0ZHMcwbqu3mVx3lqH9wOVB7zXbhxQZ-O1pLcuv-VX7t6BpMvnyw0ta6S1V30CVbGPfqIGrJwSQdJjhLNm25GZSSMYxExPWFadXqv3ci6fyMHTjzCXtMC6BFcBISm4t3ka8YWJyThyiTjYRNZgsC2SQJLBI-5g/1OWbimGZ6L-XycgxDer2G88dOlt8t_WDw9vVQFSPkP0", "Materials": "Platinum, Diamond, Bar Prongs, Solitaire, Asymmetrical, Tapered Band, Engagement Ring", "Description": "This unique platinum ring features a round cut .38ct diamond (VS1) in a tension setting.", "Designer": "Robert Corio Designs", "Name": "", "Keywords": ""},
{"Type": "Engagement", "Images": "https://v5.airtableusercontent.com/v3/u/29/29/1718128800000/XQS7Cz3rl29In69ZWR5rLw/L1z4ufHUl7Dk67Mrf-Z647VbbSB8hrMqk8owtGC7oB3UhMqOzEdXlXJ6lv1F7JFLD8fvweC3rSGjqvqG7yrnB6kHDwCCqv5HcInotmznUj7Sf0FPQ_sWL7jsxqnpOZ8qroHCFwE6NIqM7wtRgth58A/t3W-rzvkW8h935An6agZ_i70pK9AekdrVGHq-FWsDNU", "Materials": "Platinum, Diamond, Prong setting, Accent Stones, Engagement Ring", "Description": "This platinum ring features round cut diamonds.", "Designer": "", "Name": "", "Keywords": ""},
{"Type": "Engagement", "Images": "https://v5.airtableusercontent.com/v3/u/29/29/1718128800000/XPdYS7V2MT9tEy9nl1kMTg/kTw0wJRex9yl3OiZAUvIFpbiOB7ZRe2qjhRh6591a47JTwoGw6BiCVEgy_ByXakIl65o055FnteM8iC2Me7NnY8Zp-eIxT-4Fv0SgAB4Em0Dkm3ybCdOt3mP-zF94SDqUyCzMnLfmktX5etFdu0GZIynkyrhqjpjZ5XMpnScHIY/OOWAqvWzdItgeB_fomxzXjZpeX_HqG0ITV92NZd50cY", "Materials": "Platinum, Diamond, Eternity Band, Engagement Ring, Solitaire, Baguette Diamond, Bar Prongs, Prong Setting, Tapered Band, Engagement Ring", "Description": "This ring set features a platinum solitaire diamond ring, with a tapered band, along with a platinum eternity ring with round cut and baguette diamonds.", "Designer": "Robert Corio Designs", "Name": "", "Keywords": ""},
{"Type": "Engagement", "Images": "https://v5.airtableusercontent.com/v3/u/29/29/1718128800000/xOCstv0A6bY5hSQdkt6Ung/oSSPP6NeFdNbdBDSUI2FTrT2QdvjQf5Nwo5rkUBz6y3dB-ZP6vviNklpm4QgjDRt4ye4althRdkw90wnaZrTpXgZ5gujD2QxKM4MlSrZGggKbvIfN9-MhkgVucGdskg2Tv_nRhCakhPDeSNkcvVcUdjag_OkUKGTY56JQs7MwVA/wp4vvwYjOkz20VavEu379KgvmNs3yEVzUsMYAhciATQ", "Materials": "Yellow Gold, Diamond, Bypass Ring, Solitaire, Platinum Setting, Engagement Ring", "Description": "This 18k yellow gold engagement ring features a .38ct diamond in a bypass setting.", "Designer": "Robert Corio Designs", "Name": "", "Keywords": ""},
{"Type": "Engagement", "Images": "https://v5.airtableusercontent.com/v3/u/29/29/1718128800000/xkEaVes1TuvrLdAKH4NBsQ/EUYF1pIpMecW8N9vLCJITgJ4ohXEgPALfGlaWyZCysMlND_Kc-LAe4z0X559JUQrElKP5rDRloSIeJSbhOQxShm-yCDbc42gze2jBrJZjPPtFohMPZX-CwR3Mo5s0XEJgeSmh_lqAbhxUVvzSNUIsyIAkqVZagE8TaQjE_I8-oY/6gie8XXSP9fLzkHGds1_-YGhRnpTTaou1S0tQ3WCTOo", "Materials": "Platinum, Diamond, Cathedral Setting, Prong Setting, Hidden Stone, Bezel Setting, Engagement Ring", "Description": "This platinum engagement ring features a cathedral setting with a 1.53ct main diamond along with a hidden diamond on the setting.", "Designer": "Robert Corio Designs", "Name": "", "Keywords": ""},
{"Type": "Engagement", "Images": "https://v5.airtableusercontent.com/v3/u/29/29/1718128800000/xEdZWbBJtqQOhct-XYVsIg/PA9pnqGtmGMUlc1ZzFfBvH-Fdezjq4iSg4ch_PqtzSv6TIfxbOhiicnysNzkfj8thVcDPXC_metePpVe0WY0AigoblpSdyLV_0xUMSNcALiHiUQky_zUjzBRKhF95ZWgtFK4pIaSYy3q1SuJQ7yE-w/9M1_TAo1o4-900-MsxES1ZjECDOjUmdh5X5c831cdTY", "Materials": "Platinum, Diamond, Accent Stones, Shared Prongs, Halo, Split Shank, Custom Ring", "Description": "This platinum ring features a main diamond with a halo of smaller accent diamonds, along with accent diamonds along the split-shank.", "Designer": "Robert Corio Designs", "Name": "", "Keywords": ""},
{"Type": "Engagement", "Images": "https://v5.airtableusercontent.com/v3/u/29/29/1718128800000/x7Sews2I__KC6NYAooggtw/ErBr-OJmHy6hTmkUp_ygs_2SsDGmErBLqPHhXmIygXNTp9wKEGXC1krauWG6D2Vn-CGmaMFsY-EZJPqjdUSfBSNZAU7UuiSxmKYPa2pVMn7k6RZIMR00EPg-TX9FhBHp8BYDR8fXSJwPYS2WVo2Ddg/F2r0fXkQylhDWWsSkbiWg1suG2wwnYef4LNaHQKaDC0", "Materials": "Yellow Gold, Platinum Setting, Diamond, Cluster Stones, Shared Prongs, Accent Stones, Prong Setting, Wreath, Engagement Ring", "Description": "This yellow gold ring features a cluster of diamonds, set in platinum.", "Designer": "Hegeman & Co.", "Name": "", "Keywords": ""},
{"Type": "Engagement", "Images": "https://v5.airtableusercontent.com/v3/u/29/29/1718128800000/WOR8HJvCz2AJhsTrUHhkAA/oVwr9sp4SuqzwaNX5Zb2yl6ZMCY8choEbUR95XcZl_tKlpZGQQrD8_Y3DG3sOY3APaVQGv4v4ONPMV3htGxBmJq0FcgOuDMFBovU9Fbj7NI7ymID3vZHHazt4u_c5Z7hL2qagZCsd9m56JR2M89wZCJdWMxcOBD_ot8Pw4V8KcHmrrnCvzAry0wMv7Ys34YX/XqMlJt1zfMPu797nLdYnmMqI04NC4bUzjTEX51kJxks", "Materials": "Platinum, Diamond, Cluster Stones, Accent Stones, Shared Prongs, Prong Setting, Engagement Ring", "Description": "This platinum ring features a .99ct center diamond, five 3.75mm diamonds, along with other accent diamonds in a cluster style.", "Designer": "Hegeman & Co.", "Name": "", "Keywords": ""},
{"Type": "Engagement", "Images": "https://v5.airtableusercontent.com/v3/u/29/29/1718128800000/woLUn2i-zq3VR-DqDxlK0A/jSeoIaeLZgzYrgZqq8-0CKnMd75Tr8bAH7HBOrJIRA6ZSvlPt8gN-_VN5OMGw7YCw2R6Z-5B5FbGmQoHWjukorypG8oU6WRED-86nJdvauczZicc-J1O8VH1XUjlOAG7kBLwyH0KqX0itSBvjtcO6P_lFlGMnvH-BmDzV-YNPrs/YfBNseBFptid59kLQRG13KLFrF-Tr4k3NVwiv7CA1y8", "Materials": "Platinum, Diamond, Bypass Ring, Accent Stones, Half Moon Bezel Setting, Cutouts, 3 Stone, Engagement Ring", "Description": "This platinum contour engagement ring features three diamonds, weighing .87ctw.", "Designer": "Robert Corio Designs", "Name": "", "Keywords": ""},
{"Type": "Engagement", "Images": "https://v5.airtableusercontent.com/v3/u/29/29/1718128800000/wGl8xqT3ZiCajhU1WuE7SQ/AFsGJMMe7n13DBOKmz_L_M7HkRtQ9t25PyKaD8fbawYGh0AXS9itLZO3Or-RI3as0XWQ7bYBRUUSJuelJJEzlDMUzNcertZ9QFKNWSY73RJxfQjGbRfWWhMll2GsPoVD8xwLwnFNigao5VjplRCQGQmE61AO2rhimxMtQA8t9s8/tb_bdxObSzueS1GdDxcawnkdsWR4XU7Jz5ntaQx1kBw", "Materials": "Platinum, Diamond, Accent Stones, Prong Setting, Engagement Ring", "Description": "This platinum engagement ring features 1.44ctw diamonds.", "Designer": "Robert Corio Designs", "Name": "", "Keywords": ""},
{"Type": "Engagement", "Images": "https://v5.airtableusercontent.com/v3/u/29/29/1718128800000/w7u6CpVQWN_dGS4Ah8XJaQ/CLdxEUlMNZxM1Qj38KGThMLk_4S31zOsqD6K-0FLoA8Byr5HMKUk0OLPZ76_2Tcbz1IK89DXDj-Ov-cJH1j-jHWHn4wppRl1yEc4VjSeZ4OWp0upS88x-0XOi-h3H1rAJbp98ZnKqMvq6tEfETeIKkAyYqhM0twwnDfE_j6_2Wc/4JZiCzmloQKCxgLU5Vj9OMp0w4rIT56wax02wTKQenI", "Materials": "Yellow Gold, Diamond, Bezel Setting, Criss Cross Ring, Accent Stones, 3 Stone", "Description": "This18k yellow gold split shank ring features 3 diamonds in a bezel setting.", "Designer": "Robert Corio Designs", "Name": "", "Keywords": ""},
{"Type": "Engagement", "Images": "https://v5.airtableusercontent.com/v3/u/29/29/1718128800000/vREnIpaDTtRvf3wvnpy_Yg/lpidYz_ZBdGy7PyNV8ljL9A4DubJ7C6QOQ5s77TMlXZUXohYHdgwHMpGZm2cFyiZRHZZvbFR1hJuvJy5_9N1rQ4guzwL3UuUIhzX-FaUSklxQahSe9BBUu7tVOY1OodMailfAw7Gs5IW4IXFh5pRBD0mM0Y2KukzfbhTkGVpU2g/JMSGbEXFSp6ro71WSSfkVGt6qoctoNxTUzT10CMSBgo", "Materials": "Platinum, Baguette Diamond, Diamond, Bar Prongs, Accent Stones, Prong Setting, Engagement Ring", "Description": "This engagement ring features a .44ct round cut main diamond with .30ctw baguette cut accent diamonds.", "Designer": "Hegeman & Co.", "Name": "", "Keywords": ""},
{"Type": "Engagement", "Images": "https://v5.airtableusercontent.com/v3/u/29/29/1718128800000/vAygsXjIW1RLkvWp8QYrrQ/wgNMEyLILKSPO0eRe5_KCvEVSFgRz4tRlTwgwZEZ3EBk-mnnvCAuAmk15kMPax-iIrvaE4hTZMBCiqJLI3JlIIbHn-rR6eKpYgs6TZDoL8WQiEouca8lCxU9mDLYBURHOl2EMQ6-1qQ6QGb63EzCfUfkCEYCVUgQA1yaOL9RsMU/rLPNWDFEtPge6vqcChXDMPd-JRc55dHTJT6iX3HFICs", "Materials": "Platinum, Sapphire, Moon Stone, Accent Stones, Prong Setting, 3 Stone Engagement Ring", "Description": "This platinum ring features a 1.76ct cat's eye moonstone and two 2.0mm sapphires.", "Designer": "Hegeman & Co.", "Name": "", "Keywords": ""},
{"Type": "Engagement", "Images": "https://v5.airtableusercontent.com/v3/u/29/29/1718128800000/vAeCWOTZT4FbrBUjoKFqfw/nti8_Uuj4hLBOZDQOW9ZBhO7TmcpVTEtT0n2TsjLVJb1NQkoPbiJn0Why7Qf-eqesrVSUkHYOtRTy3PWh8a5bY0FymZNPxVGu2fmsP5hB3K2FjezHsYY8nO75dT3P4s_y_FvlqQI2FSRcdf-uk7996Um6j1iL5nvsDcqxvZzYb4/69jtutpQR_d-Xo1Y4S-O63OsnhgLTn63uMUsq0Ngul0", "Materials": "Platinum, Diamond, Prong Setting, Accent Stones, Engagement Ring", "Description": "This platinum engagement ring features a round cut diamond, G Vs2 weighing 2.04ct, and fourteen 2.40mm diamonds along the band.", "Designer": "Robert Corio Designs", "Name": "", "Keywords": ""},
{"Type": "Engagement", "Images": "https://v5.airtableusercontent.com/v3/u/29/29/1718128800000/uXP0qNVn1I_oqmLEC4TKeA/Ep96gaBw_W0xRA6IdMm1-XwaCJl0K1DmMOOXNo_7Tqj1t91MmyK2XhP7k5c7srV-a644iuU0Mos_p5TA-4bXFNgbBxuIFw8CL3IqBXXX1n7kub7FFQTMzmN3imbLUes2uwEGajIqgasr18-rS2FdUzL15L5KBEoQHt55tX5RW4Y/4yLp9zqfj3gTL1wQrNv1pipMp-edJntnbozzeeGBhrY", "Materials": "Platinum, Diamond, Accent Stones, Prong Setting, 3 Stone, Engagement Ring", "Description": "This platinum engagement ring features a .91ct GIA certified diamond as well as two 3.2mm accent diamonds.", "Designer": "Hegeman & Co.", "Name": "", "Keywords": ""},
{"Type": "Engagement", "Images": "https://v5.airtableusercontent.com/v3/u/29/29/1718128800000/TTpnSqnz9aOoyyj6o9FFFg/rEbkSCK-asQF50gW8sJqdgGHmv4jNQagxdiLy9RQt1ZWvBrxOKjXJDSb8YDhIvwF-CKtdCwhufG_ASR8QYuZL_SrZhDcWPPyj5wPdYUtDBpJhD80U-48EovR5zGzjFOUMu6Uo6BGBnd8HB_g3e6TmnEg5b1wOFEdPwNTW21Cm5I/mgWk_6JygcRsDAB54YfSs2E5nSOxiU8vfxsAO54NpIo", "Materials": "Platinum, Diamond, Accent Stones, Prong Setting, Claw Prongs, 3 Stone, Engagement Ring", "Description": "This engagement ring features a 1.0ct main diamond along with two other accent diamonds.", "Designer": "Robert Corio Designs", "Name": "", "Keywords": ""},
{"Type": "Engagement", "Images": "https://v5.airtableusercontent.com/v3/u/29/29/1718128800000/to-AOfq7QtlBARZHWHMbhA/KgQid0aAcrflaI8r7RJb5dEPwfN-PlHDSmt5_5V2lmijyb7LrhP3lQqKJniv86WNOgvKwMFnVmbZyqkd2h6qxaVkoNdPHBzGA9fUNbcfdsHHNs7SHlk-odghdTfv0MUynRJQ6MKg3GL4ddJZ0p7CiDyT3L_8gBdK3teWBvF2sNM/wdvxDuOqcmh1sNfACYLrkM4QNAR9ea5YIHuTjNS7gO0", "Materials": "Platinum, Diamond, Tapered Band, Prong Setting, Accent Stones, Pear Diamond, 3 Stone, Engagement Ring", "Description": "This platinum engagement ring features a tapered band with three diamonds, totaling 1.7ctw.", "Designer": "Robert Corio Designs", "Name": "", "Keywords": ""},
{"Type": "Engagement", "Images": "https://v5.airtableusercontent.com/v3/u/29/29/1718128800000/tKJS-jTVrFE5BuaIRcWZtA/6BnNlrJg0ayz0SiiRW7l72wSTWwnFz6ocdy7vBHlhK8krsHLXNfdSwJqrgpf0S4cn8rr8Hb3ndMcH5dWT-VzjBAxNPXu0XK2ysOGseaXdAlp7UR5hPXkSli_t542tDKHgTxhwffbWqw1gp3UBpBnD64Bt-oxUNKSIxlawNO2OEo/crTtAX2vvt7G6soczVZiZ5j3zk1_qxqmZ0li_u0MAec", "Materials": "Platinum, Diamond, Engagement Ring, Tapered, Emerald Cut, Accent Stones, Cluster, Prong Setting", "Description": "This platinum engagement ring features a radiant cut diamond, weighing 1.24ct, with tapered round cut diamonds, weighing .50ctw.", "Designer": "Robert Corio Designs", "Name": "", "Keywords": ""},
{"Type": "Engagement", "Images": "https://v5.airtableusercontent.com/v3/u/29/29/1718128800000/T93bZnEh4fFy0C0FCM8lAw/CDkNVSu3dbreKqzSiSfMzSC_qRzTB-s92KCMjk631gHm4Pin6mNtbglMX_xgNqqvrTqAzcsZ_gybKgARRqBf3XoMaI1ma26bQB8w9oi57EbP8kFMzV9BQLGTbS1gS9tjskKe8g4lIeOBOiqSTQNw2GzsFkK5EyVKJVkrNUmt8fY2rQtqUaQa66DMVpCkz2UH/IKPGzIymrfy3Is97kX9YEs8AVpPL2qDnVRXnnjifl3g", "Materials": "Platinum, Diamond, Accent Stones, Cluster,  Prong Setting, Engagement Ring", "Description": "This engagement ring features a 2.06ct main diamond, ten1.9mm diamonds along the band, two 3.8mm accent diamonds, and four 3.6mm accent diamonds.", "Designer": "Robert Corio Designs", "Name": "", "Keywords": ""},
{"Type": "Engagement", "Images": "https://v5.airtableusercontent.com/v3/u/29/29/1718128800000/t3M5mmzKzf_dWg-AafbbMw/JurCFDhi0HQlw4sGHKqdEzjOkPAFn8JTLAlKBMQ7pmEFGjT-8uGAgMUM9xPFnEGWY307cs-2aeOKCoVGT5fpqrfDc8gwRqi8Kzx8Z62esszkysMilbw7ROaJ1IP6x_-KsW-3gh4npkQUCfC0ZUWKjcd8BJ4Xd-YBMxPKKyGYggw/b4SSgoh7lTGUzvWGB2IGU-uDlWye3ToS6sLgrDbhNig", "Materials": "Platinum, Sapphire, Diamond, Engagement Ring, Halo, Prong Setting, Accent Stones, Halo", "Description": "This platinum engagement ring features a round cut diamond, weighing .65ctw, with a round cut diamond halo and accent stones, weighing .37ctw.", "Designer": "Robert Corio Designs", "Name": "", "Keywords": ""},
{"Type": "Engagement", "Images": "https://v5.airtableusercontent.com/v3/u/29/29/1718128800000/t2ZdjEPaiqz6w2Rr2a74pA/ryiND8rnj83WWdvian15cc6hWXcBgo2niSTvBUbdUG1Nrbb4s3TvVGbtqqLfF67clzPUrZYn-tJaTpI00EKmcTcSXymzr6FOGG5bxPUhDX6zmhVvs2osxWsak94Vy6893yklqnucazWRfuq3Y-TGbAJidxuaBNgeiJZMXBAiuec/Mf7AdTYtgL2dF3yA1oE2XTDVFpAPjYeuVWboI-j1mjE", "Materials": "Platinum, Diamond, Prong Setting, Accent Stones, Filigree, Engagement Ring", "Description": "This engagement ring features a main diamond along with ornamented side stones and filigree cut outs.", "Designer": "Hegeman & Co.", "Name": "", "Keywords": ""},
{"Type": "Engagement", "Images": "https://v5.airtableusercontent.com/v3/u/29/29/1718128800000/SvFVtmXNQeM9nzDsWEjciQ/qGeAc6_n0Cn8JXxnOegNi07xTNgrtTCFTcwl5qQTO-5K8RWTtyEu7vwrzRuH7DnI3M1lsLEpa0ZEJThyh22pIUuEwmDZOi2vWB5sMzZUAq3NNLT0p17B7tS0eO7py8EBNu11UaR60dk_hoalTOQesg/M5VctN77HglKV4bx23X8EcsedjCh3G7A7ENGGgugf70", "Materials": "Platinum, Diamond, Solitaire, Prong Setting, Engagement Ring", "Description": "This solitaire ring features a .90ct diamond.", "Designer": "Hegeman & Co.", "Name": "", "Keywords": ""},
{"Type": "Engagement", "Images": "https://v5.airtableusercontent.com/v3/u/29/29/1718128800000/s5g4QZ3EEqWG897EAivogA/Y4iV6ycWb1Vf4NO7fY2eqOvAGZOxoXtMPa5PlH54dkYK7tTQ3Ptcg6nDAVGjONqrUb2zymdiQ1o-aG3hqI1T6cXGsxIVjumvBsZmhfKrYiDTpeXGYSaI0IIzIHgOldI5JyspF_yU2RDzGWyjeu_ApdGscz1g6oOO3_PkOSu5tOE/ouiYswCvRgzSjSpSq9WhrSGmpjxTmH_ndvj-VwnrZx0", "Materials": "Platinum, Diamond, Accent Stones, Half Moon Bezel Setting, Prong Setting, 3 Stone, Engagement Ring", "Description": "This platinum engagement ring features a .97ct diamond with cushion cut accent diamonds.", "Designer": "Hegeman & Co.", "Name": "", "Keywords": ""},
{"Type": "Engagement", "Images": "https://v5.airtableusercontent.com/v3/u/29/29/1718128800000/RsvoFCul7VtWWv7bJ4bGAg/1rVqnlGAKDzzDlcNtOu7VXVUxK-FtB4xTcemnWl93iE6oCrijeW4EyTe6WAV7FRi1hBScHK3B_tMfKj_bF5AmSokuciEnVOK4ufaLQUl-uduA7SLl28E8bjcdr0G5rjWjo1Tq8COS1QsSGkrigHbXA/wvnOyDADnQpuRkN7OKidLoqPwuaVT94rIVFjIXzkrvA", "Materials": "Rose Gold, Moss Agate, Custom Engagement Ring, Marquise, Prong Setting", "Description": "This 18k rose gold ring features marquise cut moss agate stones.", "Designer": "", "Name": "", "Keywords": ""},
{"Type": "Engagement", "Images": "https://v5.airtableusercontent.com/v3/u/29/29/1718128800000/rQAFqfFVk7FK8-G3JNCnNg/VGKdOfptRpMQWZsioDdQtQwsr1Zjj71xqinKw1EUn6UOUQ9mDaEy2OANSOUsfdfwRcE-tou6-NQuBI2LrmMxhY3cPHC72oLWxEHYKAoknDQAlM_bV6BRE6UFalsjFscxJ96_GRQYVhH8cx_skJmOBg/yQLET1hHjSKKkfGoiR-jvL1T5hgclfU9n6k3B8RL7DE", "Materials": "Platinum, Diamond, Bypass Band, Bezel Setting, Engagement Ring", "Description": "This platinum bypass ring features one 1.6ct round cut diamond along with two baguette diamonds on the end of the shank, weighing 0.15ctw.", "Designer": "Robert Corio Designs", "Name": "", "Keywords": ""},
{"Type": "Engagement", "Images": "https://v5.airtableusercontent.com/v3/u/29/29/1718128800000/RjKWK8_eDN3YYjezQNGFhA/iQufaoRLgwzW8HkJ4T8MLLEnJW2cb-A-MpmKvJDlfErI_zAjrHdXBTFr-VHRxl4UvNiPotPbJA19MSxArMUYtilu-4fJ2M593PnybG1zVtcPGDv_uD1T-rU8N-TWNsdw6XoLIQCI6KbJ4LAMD7ueGh174MW0Qbs7w2zXCKRbwvE/EwKBze7jXnLzAvDml45LJB26zIppX3vXVuzregjThQQ", "Materials": "Platinum, Diamond, Heart Diamond, Prong Setting, 3 Stone, Accent Stones, Engagement Ring", "Description": "This platinum engagement ring features 3 heart cut diamonds.", "Designer": "Robert Corio Designs", "Name": "", "Keywords": ""},
{"Type": "Engagement", "Images": "https://v5.airtableusercontent.com/v3/u/29/29/1718128800000/QgGeYFHOEeEwU_nfRa3qRA/sKcNa60xIu1VR-tVdsyNXOjJY48TEeyniLXRwfMueHegt783KMLBfJhM8HNf_4f8SmfZ0mYM9zFc9Jij6T879R73CVXMRN64uQND98sVWy-mdEXujvRD7Q98TXUVUE53_bAsmeghlqGxzAuBRTq1pgSHKOE3gOBB2A_EiRlo_G2D-5uqXXdg9M6YAXlCnws7/3CLnC9AbtSvAcIkUSQIMzGobE9__5UBTSbWBAL7Ha1Y", "Materials": "Platinum, Diamond, Accent Stones, Halo, Prong Setting, Engagement Ring", "Description": "This platinum ring features a emerald cut main diamond along with a halo of diamonds, as well as diamonds along the band.", "Designer": "Robert Corio Designs", "Name": "", "Keywords": ""},
{"Type": "Engagement", "Images": "https://v5.airtableusercontent.com/v3/u/29/29/1718128800000/q-re1HKk-ParWlD2ZQgQxw/ZsBq1lvEDibu_kOvaEEqwE-Dcmd2G8JwyqyIkDf6LzNUHd_rfG3Cqm0jjXbLgSoCMkTBMkWvqa01fIrcyLIyRsbqDCc5U7XIlsHfXlQuBEwhg_xzB-OZxP-IPoM-DzLZG5d3Q5GlR_r9qs0nosEqoWU6QSeD2AmXaFDX3Og8kec/2Rw3yMg4R5veNTf4aaWnJHE40VweXQNErlsR4wMRjzw", "Materials": "Platinum, Diamond, Prong Setting, Accent Stones, Twist Band, Engagement Ring", "Description": "This platinum twist engagement ring features diamonds and milgrain detail.", "Designer": "Robert Corio Designs", "Name": "", "Keywords": ""},
{"Type": "Engagement", "Images": "https://v5.airtableusercontent.com/v3/u/29/29/1718128800000/PpaI_d6eIQKi6Mc7K3GvSg/oK_GhorhVbhhfx3IMWFX0g-xYhrkGVxKmKFhEAHCdpNG14ZVdVvXJRPJkfxPDknH8by9ddDrsfMOxz-nqpiun53f8uO9VT18dbqF68SODYoVU8iXi4005E9c7BCFBVRUOkEihQEO9Du2TggZpN2_sf4OjrKTARt7_h7hV4n7bBY/3kzYlBKtHMXHz-eqfe6n5DXPoz2kvTnlSMjPrnCs_0Y", "Materials": "Rose Gold, Diamond, Engagement Ring, Twist Band, 3 Stone, Prong Setting", "Description": "This 18k rose gold twist band features three round cut diamonds.", "Designer": "Robert Corio Designs", "Name": "", "Keywords": ""},
{"Type": "Engagement", "Images": "https://v5.airtableusercontent.com/v3/u/29/29/1718128800000/p-GWfat-HQNcfnfnTcMD_g/Ho-UQjq9kP3k5noJ-aCKAtsnXSokxh-MX2gRgy3aMLlnHAVlW3Ml7s35E1FyAtrLUz2x-JmBrSV0OkmylKXqjqF93dSaawnTPwCJiLclEOX62Yb-FCsrwCyVQKSajLyPwhcpMDvPwrAuF7SlGzjquRXOsLIm8XDWWM0KhhjYloo/8AG0Ny_6etjiOt1QKqAqleg78FuRdIKkMcqyTuWQQd4", "Materials": "Yellow Gold, Platinum, Emerald, Pave Setting, Half Moon Bezel Setting, Unique, Custom Ring", "Description": "This unique engagement ring features 18k yellow gold with one platinum half moon bezel set round faceted emerald, surrounded by round brilliant cut diamonds in a platinum pave setting.", "Designer": "Robert Corio Designs", "Name": "", "Keywords": ""},
{"Type": "Engagement", "Images": "https://v5.airtableusercontent.com/v3/u/29/29/1718128800000/oyxBdOzHMHxtBxUBBeNbQg/qm0dT_y-HBB9ChZcg0Evxfgufuw7LiJQAZm4QEMmPEX4AVb_rY54Jhp92P0RLYOGDKnRs3ylDQ7kjiRDMtKRccnPAjCmJTVFVN-gM46sr1b1GYCFxDzmdK55gy-VCxI6UlTFAQed-AmO7-Z0V4gkug/bC6ByzaZlTy718sM3XemCNEzZqaQIIAkgjNPEx6OIrM", "Materials": "Platinum, Cushion Diamond, Prong Setting, Accent Stones, Engagement Ring", "Description": "This platinum engagement ring features a 2.06ct cushion cut diamond as well as fourteen 2.4mm accent diamonds along the band.", "Designer": "Robert Corio Designs", "Name": "", "Keywords": ""},
{"Type": "Engagement", "Images": "https://v5.airtableusercontent.com/v3/u/29/29/1718128800000/or2MVnzYeXCmEaygl3M8pw/4Jet424cjf6XLoxnkPv_ARe9hx26WhJn1icb7yUHDvMcRRtn_cJZ5F2zWFTZVIisdFpk_3AXzKJHcAD7I9K1H_gS2ZDDr14Edket7OBy7zpBZyANDk7h985JYKw1pFv7CtYbGHmdPtiorcSj14MRHw/OsjYQeIfcrqSCCF0HUv739NLqpJQwkgAUvWQ0mWu9Aw", "Materials": "Platinum, Diamond, Sapphire, Accent Stones, Prong Setting, Cluster", "Description": "This platinum ring features a 1.95ct main sapphire, two 1.5mm accent diamonds, six 3.0mm accent diamonds, and eight 1.7mm accent diamonds along the band.", "Designer": "Robert Corio Designs", "Name": "", "Keywords": ""},
{"Type": "Engagement", "Images": "https://v5.airtableusercontent.com/v3/u/29/29/1718128800000/nwveH6YO66SnbKQkJZuh1w/4lpQxGN80b2C8FKZDxEsivAJiBOoi-PLtQfK8qimOOli8tUqNZZHz1Ux1cHK7V0XfYMtMP3Sn3pBHZdlPVUqOxq8_K-v3323LhVyETPV_PrWJXo92CjEK2LQWQi77HCTv2Ywct5--KJQ5jEwYmkYllT9FYMDri0Fl9Z2vfR-oyI/Kvjkg4NBrRreiqy2mfTSx5OlgmqiIjsORaVj47GI-5o", "Materials": "Platinum, Cathedral, Solitaire, Prong Setting, Engagement Ring", "Description": "This platinum ring features a cathedral setting.", "Designer": "Robert Corio Designs", "Name": "", "Keywords": ""},
{"Type": "Engagement", "Images": "https://v5.airtableusercontent.com/v3/u/29/29/1718128800000/mZT4okLzZ0QMFVdbx683mg/W5V4Da7TpO5KZEurSF67McNKyHQg9TYx6e_r3qNyuMsjQbrVxfyJQBkaxQhOpIju4NUpm3ksMD3o2mP6JK3yUhs0Q4i6K17gD7ndAUAEJTrrIM2us55jO8CAm_WWq8M7NGfH_7taj7lVldT9_koEnG5Z2ZuYUVEYvfJlqlsKy-U/rUsrksmPNVw8Kb-oPbZvzCSYREGL9EfmSbkKiZykwaI", "Materials": "Platinum, Diamond, Solitaire, Bypass Ring, Tension Ring, Underbezel Setting, Engagement Ring", "Description": "This platinum engagement ring features a matte shank and a tension/bypass setting, with a .38ct round cut diamond.", "Designer": "Robert Corio Designs", "Name": "", "Keywords": ""},
{"Type": "Engagement", "Images": "https://v5.airtableusercontent.com/v3/u/29/29/1718128800000/mxrpPikUxitZXz_I3aXSDw/8t-y1hgfPNFLQvEKIU8H9m_3zRIK8wO6gW0XXJ2wyjAo9djqSD5l5fRv3b7GaW4z5bKQPXfXWkRQtMh5zYDPFzvfnHXJ77vTu9sC5KKUH8v5l31_IJ10J1Jp6ffj5-C7gmHFB3rvNriw2G6AxE-ViDC2hBqgMkDsQeVRWX7D4EU/dbHhW3kLzDvTzxrhjnx8DTF0_2lVKpUZVQCqyOVP31o", "Materials": "Platinum, Diamond, Sapphire, Prong Setting, Accent Stones, Cluster, Engagement Ring", "Description": "This platinum ring features three oval cut diamonds along with tapered sapphire accent stones.", "Designer": "Robert Corio Designs", "Name": "", "Keywords": ""},
{"Type": "Engagement", "Images": "https://v5.airtableusercontent.com/v3/u/29/29/1718128800000/MWOvk-3yeP510cVgjsCQhA/WK2JIZ0OgwsHn6OMCVkjaJS929KdKlijvJK3oa_Znn30T4_M4ByuJN_efc1Pv6nb9zc0JTGdIIhbsjoPwFsQBQ07EdVw7RMT7GUHFqINoM-34xjgx-wR-uiK22uXOtqcZpb5PBwln8PanEGxoWnwMQ1csJfF621QcnZnHCWK71k/YrGemUTP4WD_kZQ-fa_pt660vUEFUMmICftaEStoOjY", "Materials": "Platinum, Diamond, Engagement Ring, Tapered Baguette, Halo, Accent Diamonds, Cluster", "Description": "This platinum ring features a round cut main diamond along with a round cut and tapered baguette cut diamond halo.", "Designer": "", "Name": "", "Keywords": ""},
{"Type": "Engagement", "Images": "https://v5.airtableusercontent.com/v3/u/29/29/1718128800000/mKoYZIXFrzTE1ZCAKvYdGQ/0F88XAsS5ezB3SE4lZiNqgoDkyOU2oJ3F3IlJUB3zPAhlyumKdIBWXQ8dRZ3hkTAJ-GhbMo9ceXeHlF2FM9W8Z7c_F6_UVrGbkhRUEp-jE5GnoLSYXciLtJ2Wy6DBuI9TepuMlCf36XfZbXGCdgc4Q/kl4zgMWLyc2RTboekd0eQDbg7x6ZHl1XjEvAnnMluHg", "Materials": "Platinum, Diamond, Split Shank, Prong Setting, Accent Stones, Engagement Ring", "Description": "This engagement ring features a .69ct main diamond along with twenty six 1.5mm accent diamonds along the split shank.", "Designer": "Hegeman & Co.", "Name": "", "Keywords": ""},
{"Type": "Engagement", "Images": "https://v5.airtableusercontent.com/v3/u/29/29/1718128800000/m3NyTAMlmzzdwH_K7IE5Uw/6P564MYCKLMdEdHMOqTJCWmxS2vxjnQm08AcShpNNHrSXhZB5782cLXk4WdG3CH-1l_vt2H9rap9qmpCHjIxqG2m7laTtvoWFyFO9tlzaHJlSMp3g5xOBYaT8BE0rwTb-1nXSypG2gIHh_VChYI9le5SynP6QyrgHDJmiOkXZFY/6R975-MBop4BEckzOaFWMhKehad4vXC2FXOI1HEcjkA", "Materials": "Platinum, Diamond, Yellow Diamond, Accent Stones, Prong Setting, 3 Stone, Custom Ring", "Description": "This platinum ring features a 2.02ct yellow diamond along with a .52ct and a .49ct accent diamond.", "Designer": "Hegeman & Co.", "Name": "", "Keywords": ""},
{"Type": "Engagement", "Images": "https://v5.airtableusercontent.com/v3/u/29/29/1718128800000/kYsr-dNfpSBgkSUVaBDcGA/y9zxxg1uLQqyfN74O-5j3jq53AvOikqH_gVxqNR8Ed9Q_tyzN5PRm-40g1i6G7BPvSCcBbfh4h8i4R_7f7VWFyhwtcxSfujr1N1yAy7Y5U6YuNYWnfsw5o3BUG6kx3EZIuClWcM1STXCZ15b55lO7f5_0yaQwYKk9iXsNT7KM9M/gHZuI4tovCbdpl6oKPiLDnfo4I1NGubLkCLKv20G3q8", "Materials": "Platinum, Diamond, Prong Setting, Accent Stones, 3 Stone, Engagement Ring", "Description": "This platinum ring features a yellow cushion cut diamond, accented with pear cut diamonds.", "Designer": "Robert Corio Designs", "Name": "", "Keywords": ""},
{"Type": "Engagement", "Images": "https://v5.airtableusercontent.com/v3/u/29/29/1718128800000/KNx7wAGxDF4l0gTVpGFMgg/EY997yIHT2lPsukE2QOkUc3U7TD_9f2vIImQ6LTk67vNkFk3jyZ_UdtDml1UCwm2KG51Ndo_CKsv9pdOX3XhPu-fA2nJ8QclRrUdAhIxRGk_ki4np4KBzjuVbiEajk_ngib5bLBKJ-R6B-qD7gpUEbDpXT2i8OICfEBJ8uwAYEc/EofyVyF8tiWmjSlnIML982cDR9QfPbJ2k0qEi0kwm4E", "Materials": "Platinum, Diamond, Accent Stones, Engagement Ring, Prong Setting", "Description": "This platinum engagement ring features a round cut main diamond with accent diamonds along the band.", "Designer": "", "Name": "", "Keywords": ""},
{"Type": "Engagement", "Images": "https://v5.airtableusercontent.com/v3/u/29/29/1718128800000/KAX2bfz3KNUiBPq8Hgc2vg/h9QaWGtckR4iQlHwekqTy0E7OKlYjQSPxZ2eIR6rkDyoj6XNDuv3vUuRK_BdG5alCVTsogqDIOa9ztA3PDE-_bwuW5Rd44jLS4pFz0QDbeaNBsMkQUiCe9IXJ2tes4Nqxiobw4djRKuyj8P4QBCabE4AHqbwPkGudcQnUKoYNBg/Y80kOxT8HIfnDvjeeZM-h__SFU-l0pfpTAj3-DNVSlc", "Materials": "Platinum, Tourmaline, Split Shank, Textured Band, Nature Inspired, Prong Setting, Unique Engagement Ring", "Description": "This platinum, nature-inspired engagement ring features a .50ct indicolite tourmaline with two 2.0mm diamonds.", "Designer": "Hegeman & Co.", "Name": "", "Keywords": ""},
{"Type": "Engagement", "Images": "https://v5.airtableusercontent.com/v3/u/29/29/1718128800000/K8hijRzp4F_njP3RMNGmZg/C-Tkn_A4HfyqOlitLFFoOKG4GH7_8CLx05mh4IXmTXR6oKPJ3X6vGTstB7ddMIC9PxWbHVc_oH7lvXIf9T61v_WxHUHf9u4iOOImUGp4o-DrEwiMYiymWbQbUpuWuHqpO-88P0bi7Qrwun2rraD_ZyQxdKJcCyCGYsqynYxWs18/mlN3bDe4grWY8e-pZ92a7mK49iDHJPLV8GfFkJwic7U", "Materials": "Platinum, Diamond, Accent Stones, Prong Setting, 3 Stone, Engagement Ring", "Description": "This platinum engagement ring features three diamonds, weighing 1.02ctw.", "Designer": "Robert Corio Designs", "Name": "", "Keywords": ""},
{"Type": "Engagement", "Images": "https://v5.airtableusercontent.com/v3/u/29/29/1718128800000/jyZaBv0Z9xmM5hL8Qz6C0A/ckjGJ3uTR5-FU7H2KQ0c1DQ3osH3JM0i8KqhMOhVbycIgVCWtqxnG8nWv4DMKzZlWDmcRVp6ycSX5kRYsxi5oyCRsV8WQQLa4NYwzEUUKZal3tv24Wg6sAycu6XgSmSraNMlRNuERpJoaWSwjRSX3A/nu41_vwpPwnlOVpp6BHoid2PQZAWYe3VNyHrHczMqQ0", "Materials": "Platinum, Diamond, Accent Stones, Half Moon Bezel Setting, Prong Setting, 3 Stone, Engagement Ring", "Description": "This platinum engagement ring features a .57ct main diamond as well as two 2.5mm accent diamonds.", "Designer": "Hegeman & Co.", "Name": "", "Keywords": ""},
{"Type": "Engagement", "Images": "https://v5.airtableusercontent.com/v3/u/29/29/1718128800000/Jqyn1q6X5wWOIiEQcBWYhg/BqXIAdd-68SIrya0wGUM_IMu5CTGGt0sp22frEo6ZilXKs8Douty_hSrearXDBzjI-aTYupVr5HTHZmLVc0ij6qtLSyPXREbnVNeS94ydh37F85dt_sOtqsOq5klRjqHkmJfxm4APosWTbxvqUVmaw/efcu5FJR-3CHDQKYgyJOseZZTZ3TFFcEjfYhoUC0PdI", "Materials": "Platinum, Oval Diamond, Accent Stones, Prong Setting, Engagement Ring", "Description": "This platinum engagement ring features an oval cut diamond along with accent diamonds along the band.", "Designer": "Hegeman & Co.", "Name": "", "Keywords": ""},
{"Type": "Engagement", "Images": "https://v5.airtableusercontent.com/v3/u/29/29/1718128800000/jhDpZILqCeyavYDpEvFJHw/p2XWqW4Ypb6WJXsGE1u2o1rE-cobqrxKZMLmuh6AdbhUA2m_TOtQh1s6O44abLeD_qGrkWbwNidBYewL-58_izG8vS1w0JkBi3yRMlIRhtB4it4Kw1SVjgTP14bKk2ZC4f2wb929LWFDKYCyDdgrOYaSjHPiWmL8-ile25tddILJJCf8cMPWQ51jvw_fBvS7/rq7KPj7-LcW5Sj81qskhCagsmJ1kAwKCdqNvA7B8PDU", "Materials": "Platinum, Diamond, Accent Stones, Prong Setting, 5 stone, Heart, Engagement Ring", "Description": "This platinum engagement ring features an unset main stone setting along with four 3.75mm round cut accent diamonds.", "Designer": "Robert Corio Designs", "Name": "", "Keywords": ""},
{"Type": "Engagement", "Images": "https://v5.airtableusercontent.com/v3/u/29/29/1718128800000/j8u2C_XkmbTm73_rjvjzWg/eJe-6zDJ3wjuKUcy_ykaDMTKwjHCxpBCEasmVI3Ks1xo0Z_lEuazgC7RdnwEdCDfJWKxcXBQ2XxMFkxShH46wTHXCTWGub6sb1vHQS0VoEWxeukLw7lDXOT22wULh9UQf5kTHw2eZOgfwykJwa-_gyd8M0kZvn5MXXHC25YEwsen7dWesxRIhNLXKkg1N3mx/ogJo0oQwLR-ZADY8x_xDLZ9Yyh7d8Dbnup6QgsdJGQA", "Materials": "Platinum, Diamond, Halo, Accent Stones, Prong Setting, Engagement Ring", "Description": "This engagement ring features a main diamond along with twenty eight 2mm diamonds and sixteen 1mm diamonds. The diamonds create a halo as well as extending up the cathedral band.", "Designer": "Robert Corio Designs", "Name": "", "Keywords": ""},
{"Type": "Engagement", "Images": "https://v5.airtableusercontent.com/v3/u/29/29/1718128800000/Iz04ic_VdhYEnBVEbNgzQQ/-F5Xbg4q0-aXqybfdksDDAboLnnxsohIv-9sR73ZbcMhC6g82YsXOdbiT6kVVgUuShpiIztALb-JqbmSiSl1wRR_AvApqtVmKHWUB7cvwEr4JqXDygn75aW3Vmk3Ne8V5Jhe2eYGf1DkzgHMlaP2z7ZUO-afosEjl5-dgZiHw8M/lW0WFvFTGeurWPgq60lsZGBkMEv2qmv05UqzcbhCn00", "Materials": "Platinum, Opal, Prong Setting, Solitaire, Engagement Ring", "Description": "This platinum ladies' solitaire ring features an opal cabochon.", "Designer": "Hegeman & Co.", "Name": "", "Keywords": ""},
{"Type": "Engagement", "Images": "https://v5.airtableusercontent.com/v3/u/29/29/1718128800000/idoY8HEzY6m10RDl2AO5jQ/FFqC23jM0tLCnBD751S2fgty9YagPXAtUMt0MeTj3OjOdIQefsFPN5FbFWDNdwq8II-L3L67MkfAlHepsvp5MdZTi3Po13EMYun3vc_76ykqC36238GGEKr9mxroMkJLxcXQn7MZ01ZD5jtbg1vCOK1HKlIRwjZEErhXFi1LaAA/RcWtRwmteTeKY1Kh0oOm9BQeqjiVho9FsH7mBqHWPhQ", "Materials": "Yellow Gold, Diamond, Prong Setting, Twist Band, Accent Stones, Engagement Ring", "Description": "This 18k yellow gold twist ring features a round cut center diamond, weighing 1.8ct, while the band features both 3mm and 9mm round cut diamonds.", "Designer": "Robert Corio Designs", "Name": "", "Keywords": ""},
{"Type": "Engagement", "Images": "https://v5.airtableusercontent.com/v3/u/29/29/1718128800000/I03I7MM-45_4tO9-vQIqxg/KCXE8d_amBbpvjOSgijkXnCI87a-BV4lrta2GHtseM27AamzdAtjDvIIeVP_-LAyQ14VLZM09WRqSRsyIlDJJpzyET34-10fxZqJIg13I7AWQ01t3av1LaxNDEiZe7EvACVd3dHTeq0sxXU0MuZoo5WLOnYmviYlI39PIauQOrFTogA7NOeSudc1WVXpcrZCzjJarv1tcDakvaYbi1b3ZA/QylYohLN05Ur_OF_VsjYxzXeC1sE8PyjHIjbjiwUql4", "Materials": "Platinum, Diamond, Accent Stones, Prong Setting, Tapered Band, 3 Stone, Engagement Ring", "Description": "This ladies' tapered shank engagement ring features an oval cut main diamond along with two other accent diamonds.", "Designer": "Robert Corio Designs", "Name": "", "Keywords": ""},
{"Type": "Engagement", "Images": "https://v5.airtableusercontent.com/v3/u/29/29/1718128800000/Hx2yTjg0deJ5aWRQv6DjLQ/_iobskVhj_vtLiC7prryaZytWTKUZcBJC4yWwOKSPY40jrhDHk2ZmiTuBQiOa7AA-2AmkKsW5xxiWEpjsGGuSD1F9BltnRq9eCz8O_zUlIQB6fiSnG_xX9bdav0QyOwAIAeMl8itK142EGJqXoEh36NSQ60cMILyOnL8bvIWEQI/Cb_KAsM0pr9M_-H-JbNUA3VpVaF1TE3di7VoTUsCUTo", "Materials": "Platinum, Diamond, Halo, Claw Prongs, Prong Setting, Accent Stones, Rope, Shared Prongs, Engagement Ring", "Description": "This platinum ladies' ring features three cushion cut diamonds, surrounded by diamond halos, along with additional diamonds along the band. There is rope detailing throughout the piece.", "Designer": "Robert Corio Designs", "Name": "", "Keywords": ""},
{"Type": "Engagement", "Images": "https://v5.airtableusercontent.com/v3/u/29/29/1718128800000/hTVo9oVB-gVu6OQCkU_Ncg/IYd3i6caEG3u3jP2ZV1sZZXMrwv5UfCFUTmszR92swk2VdAs4kxquRZ8gxaHpvC4E8i8h1nU-ddsAHX1EC2XOX1kdEBfddKxpsfMGC1xskGuJVsW71BengDwwg_fbpQCZDv3j0DOK89wgEaIY1p38-NBnzQ52fnie67JITR586YY8dFU_8vlNagTzXOOK8Jr/BQwzjiIuW7GAuQmenyoRrJWSeRrfich0YV8HsW5B3HM", "Materials": "Platinum, Diamond, Accent Stones, Prong Setting, 3 Stone, Engagement Ring", "Description": "This ladies' engagement ring features a tapered band, an oval cut main diamond, and two round cut accent diamonds.", "Designer": "Robert Corio Designs", "Name": "", "Keywords": ""},
{"Type": "Engagement", "Images": "https://v5.airtableusercontent.com/v3/u/29/29/1718128800000/hmb91vufx_FlKBTrCrYazw/xEianNA-IAY8_Zl0ISpG3-S7bq1bOQFcObXts8UQmkF0O1Vb6N1qq9vxaWDIBAJfY-hHG5mtcFTVL9pNC3QJIR6CyqQKTOXSObBHchmyiXz7NE-vQKxdrZHuY-OlgQeZAJehRaPcV1kQBgyIf4NSoA/EMXOty3XgJ95uRAsbqzASiag_JjYuryTpsY2MSmZCzY", "Materials": "Platinum, Diamond, Accent Stones, Prong Setting, Cluster Stones, Engagement Ring", "Description": "This platinum ring features a .73ct oval diamond main stone. Also featured are two 2mm and four 1.5mm diamonds.", "Designer": "Hegeman & Co.", "Name": "", "Keywords": ""},
{"Type": "Engagement", "Images": "https://v5.airtableusercontent.com/v3/u/29/29/1718128800000/hL2KXDywlyj8bkkcO3p5HA/wscVbUzNeK6P5XmxgUncGKEeSdjx5bEbbWrIqx6ExTMGOx7e-JztbpfJjbJWSSICjdr0Gq7tNT43Khrw5Yp_2Mh6H3Eqi9dqyHUdf6iY9HZG7x8jgGS1cdJbwRIDyhbU9HFRrVPHHvuUHeQh6czrhg/mi3aanTxnT8XrkbqaWtOhSO0BTc07ejd9TwZgEy9vvI", "Materials": "Rose Gold, Diamond, Accent Stones, Twist Band, Prong Setting, Engagement Ring", "Description": "This rose gold twist engagement ring features a .90ct main diamond along with accent diamonds down the band.", "Designer": "Robert Corio Designs", "Name": "", "Keywords": ""},
{"Type": "Engagement", "Images": "https://v5.airtableusercontent.com/v3/u/29/29/1718128800000/HJeKC1dGzVrR_6HJclSz_w/K5C3beO9lFRZVdVjyPE5yp_XY-KEzDWpYnaWOiBORLKgmXJRBYeNlrOT3B9apNAO24pmm1KfXubY-MyE-dTB4vgdpCsZfbguP09l92K5SDumxnkDii2poPyDFh4xLnMEhpC0y68tmcE6w1UhM7fUGLSnIpvcskYCYYCw6M4An5Y/2uRRQYXN8ULNFz0lTt-pwg_alDLU7dHKL77ppGd3ESE", "Materials": "Platinum, Diamond, Accent Stones, Prong Setting, Baguette Diamond, European Shank, Engagement Ring", "Description": "This platinum ring features a main diamond along with oval cut and baguette accent diamonds.", "Designer": "Robert Corio Designs", "Name": "", "Keywords": ""},
{"Type": "Engagement", "Images": "https://v5.airtableusercontent.com/v3/u/29/29/1718128800000/hBTvvrFQ_4loNm8e51bo6w/YjPC4aUo8ApH50pbdM1SVyF_aGbVy-GRlc-Pgm18F_vihUoiahsNZlSy45QT7ZLxBPi5gUAlK_Rhsk5ZiakgBcVs2xt0rWzInRYg0fnk8G_89fXDBnvdjQSv7RXjvrUnd2E9aXOLfMUdheKsVTfaazSTos_kY8qWViDys6qa7nE/CM6mqzNhjImmbIsGdhW4fPSt5rKqnhWua9F25txqU7c", "Materials": "Platinum, Diamond, Prong Setting, Half Moon Bezel Setting, Accent Stones, Milgrain, Engagement Ring", "Description": "This platinum ring features a 2.44ct main diamond along with two 0.52ct and .54ct side diamonds, and sixteen 1.9mm diamonds along the band.", "Designer": "Robert Corio Designs", "Name": "", "Keywords": ""},
{"Type": "Engagement", "Images": "https://v5.airtableusercontent.com/v3/u/29/29/1718128800000/Hb_3F8iqOyH0uPP4qep4cw/SnBhgCJYlisQXn6wY5bV0aIjq77WuKfb5V6Jy2rCYHJvQRfiQrsoogqCZi-2cbIjwtQc8PNlVJ4scpzemDeIes85YXjyE0ttGjgEhpGaOyI9QQRrEgEA-TLK_DJNunEPXiP9UZowgnv7DoL7zYezmaoI8KkpSk50UG_VHQIlHa3Bp3w7L_BqA_srS128-hk7/tq1uCUU96naJXszZUXBliMKWYBRHRdmiU3BuZQjD-QA", "Materials": "Platinum, Diamond, Accent Stones, Prong Setting, Engagement Ring", "Description": "This ladies' platinum engagement ring features a 1.12ct main diamond and four  3.75mm accent diamonds.", "Designer": "Robert Corio Designs", "Name": "", "Keywords": ""},
{"Type": "Engagement", "Images": "https://v5.airtableusercontent.com/v3/u/29/29/1718128800000/G-LB7Dp1ICRmmM9bLM6E6Q/wt0J_yCPEuzVs88R7jgLLCaT8crS6t02ImuZUryAdueGTxafGnR0W9jf_U47zefsfX1vYWiSqbrAV4LLffGGq6atMZd9lyYCgEqD-HDSVoNbe453RtjULeA6-Sy5UDAz8lQ_ijZ56vQN2j8NjA6Ejw/8XcqCg2NZJ836VSSygY78_UnTzHF4uiDirlyD-bK4o0", "Materials": "Yellow Gold, Diamond, Prong Setting, Accent Stones, Engagement Ring", "Description": "This 18k yellow gold engagement ring features an oval cut diamond, GIA certified weighing .72ct, and eighteen 1.75mm diamonds.", "Designer": "Hegeman & Co.", "Name": "", "Keywords": ""},
{"Type": "Engagement", "Images": "https://v5.airtableusercontent.com/v3/u/29/29/1718128800000/FKpY4PsuKdNP3AMcimcxdA/O4pt7s9BSYUVOGX3MMCUEJJDdam6dvcRd-FmICMaFPwTllHdkvukyYNKpkhiShJ6_cMjYseOzRzRpaiT5KUbFG1HHFemoYhoZLtAMfARBIadvIQ71w7qReeTLPOWdPMmn2U8IO2g6WHNJhOr1FJ3YwyuXV0mx6iN2kVXpHJqUPY/IQ2mSdFWKoL4QHPTA97DpOi3BdhvoCmY-DRkqKriptM", "Materials": "Platinum, Diamond, Accent Stones, Prong Setting, Engagement Ring", "Description": "This platinum engagement ring features a .70ct main diamonds (VS1) with two round cut 3.6mm accent diamonds.", "Designer": "Robert Corio Designs", "Name": "", "Keywords": ""},
{"Type": "Engagement", "Images": "https://v5.airtableusercontent.com/v3/u/29/29/1718128800000/fAvLVUHZHPQHN9u8BJUhvQ/DB_ULFIfIfSWzbGq2bjb-jjnv318NGmzYVNLQrfd4lCaAR0YQ7HQIoydQI8QIKtt_9QLYo2DnKEfOzshCwTavwMWXVheuIwMDhKnlaDHVws-TJNd60ppw45HZDDilNqTqJN3QNiHfxkZf5-w3SF_JJInnsRPMcdBLsz_Cb0OgNw/qQhYBDEfPCb74DllcLb24NwbDR7i-5Ab-kggi910gzs", "Materials": "Platinum, Diamond, Split Shank, Contemporary, Halo, Prong Setting, Accent Stones, Unique, Custom Ring", "Description": "This unique platinum ring features three cushion cut diamonds with round cut diamond melee in a halo and along the bands.", "Designer": "Robert Corio Designs", "Name": "", "Keywords": ""},
{"Type": "Engagement", "Images": "https://v5.airtableusercontent.com/v3/u/29/29/1718128800000/epfAMpJSRcVrga_JJGEE8A/LCIgSMEpwo2tbvwZsRMNP8XIrdWitDFg-n_R17ADl2YGh1n-aiq899D1_6DlWpRbySLdKdz03214oOrMBaQYLdd4369RkKx6oaV1zlQ2bmSqe7JooJgSP57gQrajQ2-nDcZQEhOG84cDVQQ-MIx3Zw/kHtfJ_JcRFdm-qa8IUZ_gOdjfImOiZAZnkCm7O01mqc", "Materials": "Platinum Head, Cushion Diamond, Yellow Gold Band, Cushion Diamond, Square Prongs, Prong Setting", "Description": "This ladies' 18K yellow gold 3 stone diamond ring, set in platinum, has a center diamond VS1 clarity with D color 2.21Ct. It is flanked by two round 0.18CT round cut diamonds, totaling 2.39 CTW.", "Designer": "Robert Corio Designs", "Name": "", "Keywords": ""},
{"Type": "Engagement", "Images": "https://v5.airtableusercontent.com/v3/u/29/29/1718128800000/eEqWP_wYNiuQL9AvdI6cmg/Fyr7kPuXDY9ZYUu-c8C2XAu8csCg3AcyU-b9xd61psT5V1I3JcY3niJLmbR3Hisj8AjgkeLHfsPCFLhEz4cncWzG_edAhcAOHmsgYFNolOEq-aya-sTjbaeonp58cicyKarTQ0_wPzl9ICXRewkkg-BlMxOnSuucT3VMTmqRkxk/bCVYQTR8o0XN0j3LjUCBieJrfZw6VwEYEjtSj_rjfn0", "Materials": "Yellow Gold, Diamond, Accent Stones, Share Prongs, Engagement Ring", "Description": "This 18k yellow gold engagement ring features seven diamonds.", "Designer": "Robert Corio Designs", "Name": "", "Keywords": ""},
{"Type": "Engagement", "Images": "https://v5.airtableusercontent.com/v3/u/29/29/1718128800000/E0GMWjafAGfL1Ari4KzjEw/rPj_Hj_H4S8f5W1TQVnjmzegDoJZaStFigFpqT6J-cgR1BeO61Zys_gCmervbzC3jD3Jr_A-K9CE86Ldvhd_6sQE1ZlTxzcvwNALJInCo6xUABE4vwMhCSb0_8miGVyqHss-HwFzqmt5kwgJz25_uM5nVtrS0htzsyK1n90_coY/xQ6hcTsKX7YWDFLyOAtAPRvdGwi92-_b9ociwg8MZ2I", "Materials": "Platinum, Diamond, Accent Stones, Prong Setting, Tapered Band, 3 Stone, Engagement Ring", "Description": "This platinum engagement ring features a .94ct main diamond along with two 1.8mm accent diamonds, set in a tapered band.", "Designer": "Robert Corio Designs", "Name": "", "Keywords": ""},
{"Type": "Engagement", "Images": "https://v5.airtableusercontent.com/v3/u/29/29/1718128800000/DROyzBGt34GhTG38YfjUWg/uxUVkbNO-4E-tAjhBFtPulBr3pUUzRKm_v6_r0yc_TuJpynawHbUF0dv-hdcP12j_2ZZSPgK7vsR89Gcn_mr3VGyWVjR2Vn5ICR7zhdA7yBMfbc6FNmRkQnoHtz5zPYs6Qkoy5jiOuWC6BGM5_GH9A/A9MrO9BtdYZh-iCv8rJIDKk2J2yyHur7-ij4sLLEIec", "Materials": "Diamond, Platinum, Accent Stones, Oval Diamond, Prong Setting. Engagement Ring", "Description": "This platinum engagement ring features a .70ct GIA certified diamond. The side diamonds range from 2.5mm-1.6mm, starting from the center.", "Designer": "Hegeman & Co.", "Name": "", "Keywords": ""},
{"Type": "Engagement", "Images": "https://v5.airtableusercontent.com/v3/u/29/29/1718128800000/dmcMwiI6yVUgKxp1z0MWlg/zu93S8QUiVNT2-MjDZR4d27wehJWSrknclExGMcbnZ5rET5_A1Md3-TOEnXV2uNDrTag9S9jO_HnuutGCalqgAaZVwDzGrcm1uXoEWOq5DojEFawXXeJXCo0Ufw4LG1Grz_9SKEHu7FjT6oiFoVVjzNCNhsQh6sr6NlH0RkonzM/C6mR84g40GGaKn_Xa445H9mJj23vE5H8lHobFLkhLyI", "Materials": "Platinum, Diamond, Engagement Ring, Radiant, Split Shank, Accent Stones, Prong Setting", "Description": "This platinum engagement ring features a radiant cut diamond, weighing 1.03ct, with round cut diamonds on and in between the split shank band.", "Designer": "Robert Corio Designs", "Name": "", "Keywords": ""},
{"Type": "Engagement", "Images": "https://v5.airtableusercontent.com/v3/u/29/29/1718128800000/cxj2_PdrS8heB_fZzWv1tA/ATaJp7TkbzfJ3bnDSI__QvfAYeE44RR0HtiT4pnBLwHp49lZWyo5SWvWmQb9JnELn0HogkwFanmekmHW5PbRkWONVTGudm3yF94qj99rfCgedFQDpqho0FKqvHSuHNNyYz-b4Svz5Y6lf2Go54Ahp0xDR1-EnHrg0L8V_qJUfgKUUGYoDMhX448UEFNAaRAH/inykgydE2ivciUjLBgy3rNt97OqJQp94Ge6Z6GoOh04", "Materials": "Platinum, Diamond, Pave Setting Diamond, Accent Stones, Criss Cross Ring", "Description": "This unique platinum ring features one hundred and forty eight round cut diamonds along the split shanks as well as one .52ct princess cut diamond (E VS1).", "Designer": "Robert Corio Designs", "Name": "", "Keywords": ""},
{"Type": "Engagement", "Images": "https://v5.airtableusercontent.com/v3/u/29/29/1718128800000/CgVJscJKrORItkDYOMe8pQ/UJE1L8o-eIX4qYJZJtxej1JEY-fNzIyHtFAfU3oGvMWyF1lfxmWBQworepIGt_BjeDaHIXzKYzYcgyX8NLu7HIwULbXdUvVyz7Z2CGq0fmzW814d1L2GoCJkfI6p6cd98_bEx4qQPaVoYHA2Lzfwhf8bXvlUcjt1lff04J2jljU/dEwP7wexIKQpgsP0OlOoSmmJXRxwI5yMkxFOmaonIEU", "Materials": "Platinum, Diamond, Accent Stones, Shared Prongs, Prong Setting, Engagement Ring", "Description": "This ladies' platinum engagement ring features a 2.4ct main diamond along with accent diamonds along the band.", "Designer": "Hegeman & Co.", "Name": "", "Keywords": ""},
{"Type": "Engagement", "Images": "https://v5.airtableusercontent.com/v3/u/29/29/1718128800000/c22mMLYxpSw-yx6amrjGQQ/dGtZrxZZokm--WnBNxBkNXuWSwXeJAvag-dPmXrxW3dC22jUJVtiwymU17qmPjRyYDGS9HailFhb1ldG9_f6md9_xFFtR22G8vVgLNQLFkyOKvAoSWZjBhaBVKKLf_q6V6T3WiH_f1SytMnM4bPywKMT32pOuEA3CH-M_p5f5j9_fBXhXXB43bwyR3WsVm3w/jO0mfsrC_Be7ieNqr3uN-rXx9o6ZKPABlEEwuiaDAAM", "Materials": "Platinum, Diamond, Vintage, Filigree, Bezel Setting, Prong Setting, Accent Stones, Milgrain, Tapered Band, Engagement Ring", "Description": "This platinum antique engagement ring features a main diamond along with accent diamonds, filigree, and milgrain.", "Designer": "Hegeman & Co.", "Name": "", "Keywords": ""},
{"Type": "Engagement", "Images": "https://v5.airtableusercontent.com/v3/u/29/29/1718128800000/bjPs2y44D4z-DgLXUdlGpg/l6yU98HxGfkEJXPvj8puznBUl4yRoXXEqFQc5qTdwCOuxTNGjpVz9BbLR_Obb7DaJE43Ei8FbVt-zanc2QQ5GAl6pkcR_Auo_nLsph5hunYdvyqeST4KRePyMa_fXpCm-6zmV-xWyJ1BafTFwDPQqjBJ6tzdgA2Tkp2_FI7P6pg/tlcowQQytwE7iZYTQo9_FX0GbwE3b2c51BeJ2o56BO4", "Materials": "Platinum, Pear Diamond, Shared Prongs, 5 Stones, Engagement Ring", "Description": "This ladies' platinum engagement ring features a pear cut diamond and round cut accent diamonds.", "Designer": "Hegeman & Co.", "Name": "", "Keywords": ""},
{"Type": "Engagement", "Images": "https://v5.airtableusercontent.com/v3/u/29/29/1718128800000/BEWQtIE5xzKCnZ-m_-6EdA/PPfKfO8A8vYBOc8gUsSwYNazpMXosPGxBWKnGAISx-kdGv3Wbgn6Th4y6pBIj8bPqiuLHHLpeNik490kS4nN68w1s0sFGHDX0UQlKVzv9BCFcOWhAFUGK41Y5z9TztbsoUATiTWXiT1iSWwHpxAd3_G5YRvfnO7z1ssFr6goDB8/as3QkdKeMs3OZTNihT9hIF9306pk8ijKGf1-xeBfXcg", "Materials": "Yellow Gold, Diamond, Platinum Setting, Cushion Diamond, Pear Diamonds, Prong Setting, 3 Stone, Engagement Ring", "Description": "This yellow gold engagement ring features a 2.01ct diamond with two pear cut accent diamonds.", "Designer": "Robert Corio Designs", "Name": "", "Keywords": ""},
{"Type": "Engagement", "Images": "https://v5.airtableusercontent.com/v3/u/29/29/1718128800000/bEs9hIaefXoLaQ0_dGsQgA/PDLMiujB8yWKrD-Quju6-jwPsYG6cB6JjoJtgTNXnpdjrntOEsar9aSU3ZdQhT4G4VMp5gS8s9VT4Bq7Ayw425fm0rnxFWswmuaTVN-T8P7Moc4OlDbKNxnvxfvgq2Sxva1uBAE5K9q6AWXjix3XWtbPxpBbtKoxhs9sNGN1mzyNM5QUl0RydnmESjcnQOVT/8YwO8WEp7xvgTDUkInjkHqqOKfGAnKc6KVit1ReDzfM", "Materials": "Platinum, Diamond, Channel Setting, Prong Setting, Accent Stones, Engagement Ring", "Description": "This platinum engagement ring features a main diamond set in a martini style setting, along with accent diamonds set in a channel along the band.", "Designer": "Robert Corio Designs", "Name": "", "Keywords": ""},
{"Type": "Engagement", "Images": "https://v5.airtableusercontent.com/v3/u/29/29/1718128800000/Ar0v100WrrPpniLkM5STtA/cub0khGhXM-cfc-enbmto2cF800o4FSIaRc5PbD252BGbeRo8jTZ5qlsF7F3XuOm8V1tbOUtlE5JUmV9W7sFbj_eyVgwas1NQcHhri8ZDYP9_axB5GQxfPhqqK0ME_XgsQytK5ycdvpKUEnoUTQl_cnocYysWtMDK-zrv2gZ28s/oeW1__56mOp20loc0mpTQERoTH7Uo5c9zl1Y39fHyFI", "Materials": "Platinum, Diamond, Claw Prongs, Accent Stones, Prong Setting, Engagement Ring", "Description": "This ladies' engagement ring features an unset main setting along with two accent diamonds.", "Designer": "Robert Corio Designs", "Name": "", "Keywords": ""},
{"Type": "Engagement", "Images": "https://v5.airtableusercontent.com/v3/u/29/29/1718128800000/_NFWShqH96TV8EM7Hp46aQ/lcykosLmquANX7PyaBOfeYRORaNznwfn3n4ZmNnguXoln-qAmmV4oSU3QRinQErFUQrzsMSB3urPMvUEEsxDhIllojbimCtSiFm9q2ObGDikcVQiRU8gbgjRzbAGdiYscI0zNhobBbeD2Ol15Blfng/PZLKuaXCQUQaGmqr1xJ21TKIrBO5l9Sm-Dw9HlUxBB4", "Materials": "Yellow Gold, Diamond, Emerald, Accent Stones, Prong Setting, Half Moon Bezel Setting, Platinum Setting, 3 Stone, Custom Ring", "Description": "This yellow gold ring features three stones: one round cut diamond and two round cut emerald accent stones.", "Designer": "Robert Corio Designs", "Name": "", "Keywords": ""},
{"Type": "Engagement", "Images": "https://v5.airtableusercontent.com/v3/u/29/29/1718128800000/935r1JHq5KHDlznKtoC5OA/8EesOzDrVCAmlfZDC43djv37gPk-DYQyvQ0SFCU1C67G_bYCu4sMnXBqmIojhJrNWyqjkipp8QN6DhwDRMFYZZSD8XlCoE3DP9kcgxbg3qnPZ-2pyxJglhXDt8M4wU5Zo1YEsqICRVEZHC_ohpcOsz-xK53Msey9sH9Q6KEQZ0g/D68mx-AE_4Rfz4hT0PU6R0KHk_-A58z3vt5nu_PZSjw", "Materials": "Yellow Gold, Diamond, Prong Setting, Solitaire, Platinum Head, Knife Cut Shank, Engagement Ring", "Description": "This yellow gold engagement ring features a .67ct round cut diamonds, set in platinum.", "Designer": "Robert Corio Designs", "Name": "", "Keywords": ""},
{"Type": "Engagement", "Images": "https://v5.airtableusercontent.com/v3/u/29/29/1718128800000/528Vh1I75xAmrSidqfLwwA/Izfqpszz2bucJ3HUDwqL5MCQ49sjhnoooiN-ImI7lmxaEJfIiXjQg7ZeqSR5LK0sZnJGqQ0KAOgNaAngOJus2vH3jqZXI9iivGemV7t3dZ04ZSiSC4nSlGMLFlmUXRfAlJ24A3MJmnzwq_GB9hr3gIypNW-fqpRrOE4uM9IrMDU/RdFQ5bgR0TMjrm578M-suE0lkMjdFDzy_QdPfNvIp_4", "Materials": "Platinum, Diamond, Prong Setting, Solitaire, Engagement Ring", "Description": "This platinum solitaire ring features a 1.33ct cushion cut diamond.", "Designer": "Hegeman & Co.", "Name": "", "Keywords": ""},
{"Type": "Engagement", "Images": "https://v5.airtableusercontent.com/v3/u/29/29/1718128800000/20SNgqLURdhVs_c_X5JfKA/PmE0RFGe7CVMWSby-IQk6x2Y4wihhv5Y2tSexjktWnaa3vDvwqRcOVRaf7n79TPSlmwD2vpR73XHzKogd-hiu88kMq7Kj6hOEcHgeUTzymZwarDXWTDVZZB63MLfu47q01-DDbgQSBF4vgsynqMEUkImMpCkzeIkqxtaLwNJhHQ/GRBPkluUSyUpGIY5ABvGNftILp21RDYYn7S3M4urdjk", "Materials": "Platinum, Diamond, Prong Setting, Accent Stones, 3 Stone, Engagement Ring", "Description": "This platinum engagement ring features three diamonds, two of which are princess cut.", "Designer": "Robert Corio Designs", "Name": "", "Keywords": ""},
{"Type": "Engagement", "Images": "https://v5.airtableusercontent.com/v3/u/29/29/1718128800000/8lDOAIIYlq39pbsT9WLPOw/3ZvCrVMs4nDh-Zc57gQxrx2Os_qyACqav1VoavkYRzNW1pLDrE8s8dOYCtTnqwyENYdcDjJyz2FqzLS8485bCqCo-kHASMnwLZWCURSr-SgWcqo-Bss83CC--tIwq_q81f0M-5C8dnEgeUYjxOIVtWC5Q6HrLfGcabC8YbpBE0Y/p2Ax77QAW5P5LYc0SwRztURfQny-dSEeE3cRQt47gcw", "Materials": "Platinum, Diamond, Accent Stones, Shared Prongs, Prong Setting, Engagement Ring", "Description": "This platinum ring features an oval cut main diamond and 2mm round cut accent diamonds along the shank.", "Designer": "Robert Corio Designs", "Name": "", "Keywords": ""},
{"Type": "Engagement", "Images": "https://v5.airtableusercontent.com/v3/u/29/29/1718128800000/7Ojk8516Wh-A4eLQan3TzA/vzEWEMFXtNPF1xFaMzxM5FwL_GaVUmZV0Bm_zUNMvNO5ljHRyi8Ps0_NVrXOYY5YJowySRRZ-XBw9ykWPwWNgiyjB5czpnTtCLXTS7LS-wqLh7AXicpiR8Rz_Z8EKsnoaCau5Q_8326s_TxGvspJt21dez4U3jH--v1hI_V5Nio/NZol-EegxWpH_pfvsyRx0V9-med7T87LCklq6Oo48YY", "Materials": "Platinum, Diamond, Engagement Ring, Prong Setting, Accent Stones, Cluster", "Description": "This platinum engagement ring features round cut diamonds, weighing 2.1ctw, with a cluster of accent diamonds.", "Designer": "Robert Corio Designs", "Name": "", "Keywords": ""},
{"Type": "Engagement", "Images": "https://v5.airtableusercontent.com/v3/u/29/29/1718128800000/6OWloWBTrBo6r8vqFdwUnw/QpRD1Wo44Ht7LeCNPeKzBZxYJpMpsycMqzKjzFd9crtjPcwrTXe5wHa6J2XNhq6UvB_yBPiyXvNAiPCHY86FkA85afpGU67KqU9bnConCsIhg8FK0nWDhyH1CMQi8AwCYqPwAICsL2uOXVOOou2Npq-L718gTEK03GPW5KxzK3c/poW0A1P4A9x4qU_iCGFNy7nLSrEONYxWHSMeDnjOmvA", "Materials": "Yellow Gold, Cathedral Setting, Prong Setting, Engagement Ring", "Description": "This is an 18k yellow gold solitaire engagement ring, unset.", "Designer": "Robert Corio Designs", "Name": "", "Keywords": ""},
{"Type": "Engagement", "Images": "https://v5.airtableusercontent.com/v3/u/29/29/1718128800000/5Q7uu1h4O-qR4uG8E1QrSg/kbSdBBvvG0lbRkW7Btrm-Y3Vd4v9VLrav-zKsNHNh_l3mW3Gw0nQyq2uZ385YIA9zqngaLF1C4cNPWBBNWmlJmhUDlrvZR1lM0WwxlQ9ZwxBJc2IVMGodRLxnDPCYk7wTBiGb3fkD6jO80dm7IjztloOWssnDoI5wpEatq8AtjmgQX58-rxSrG-NatS4PCaI/O_CPaMQtw_YjE0yVi7UQVzuQsaEaC4yQZwNNStWs_0Q", "Materials": "Yellow Gold, Diamond, Platinum Setting, Prong Setting, Engagement Ring", "Description": "This ladies' engagement ring is two-toned with 18k yellow gold and platinum. It features three diamonds with a trellis detail.", "Designer": "Robert Corio Designs", "Name": "", "Keywords": ""},
{"Type": "Engagement", "Images": "https://v5.airtableusercontent.com/v3/u/29/29/1718128800000/5-UnfKXACfpY67nAv9kJfQ/13rf45td7wPd6776M10iP0jQ3A2Ptzm6U_Ru6JufGTdcL1VZTGqRqC7UWgACqCK32vZi883KY6ANcXBuvHYv2FICSGlvj8hLr1pvQ4pahpgtS_-yxgZtXg7HZ7mw4iUZpM7H8juHA0ucantvsnUfrA/6gAIE6be-0LE2R4PBj2Ft206bvTPhLZB6klYuFaZ_JM", "Materials": "Platinum, Emerald Cut Diamond, Trillion, Engagement Ring, Prong Setting", "Description": "This platinum ring features an emerald cut diamond and two trillion cut diamonds, prong set.", "Designer": "", "Name": "", "Keywords": ""},
{"Type": "Engagement", "Images": "https://v5.airtableusercontent.com/v3/u/29/29/1718128800000/3mfZOkJRz1ll22JsThOpjQ/bCmExJWiGj7fll4DhaF2YcGP_py5yHKyNTIZrQVWVgAdooaUpIkbmcK8F0XiLRx086LbjEahWRCw3xiGAFXz3vnDhOR5keKOCuNnUdIkLg0fAkf3fEIOhxQ0IDeR-Eu-dxyLCWWzgQGydzsMPaynuw/rYfH8AIQUdjcNduT55cuwGIE8PDb2aUgep_npGJAJnc", "Materials": "Yellow Gold, Diamond, Sapphire, Accent Stones, Prong Setting, Platinum Setting, 3 Stone", "Description": "This18k yellow gold engagement ring features a sapphire main stone along with diamond accent stones, set in platinum.", "Designer": "Robert Corio Designs", "Name": "", "Keywords": ""},
{"Type": "Engagement", "Images": "https://v5.airtableusercontent.com/v3/u/29/29/1718128800000/3gQ4qhVTI6bXrCqUKMaLfA/rNGrZH8roOGNf7g3ybzSNUMir0YBkQMKxtIUkHz_JJkcaZv-LxObIrceidszuccr2k0EMU25Io5GXqr7jpQGOHzq7gUdubNxFlyF597ssa6MH10V71e0tq5QX9tvq43ytOBIw1JEQqRJvYRzo53ZcnwaUK67JiGkfMPfb_epzJuLGqiWEFynUsM9vFCX_obm/VL2c0V12bh08qADx4IIis7BdhflV4XTlwkWVjY04RG0", "Materials": "Platinum, Diamond, Baguette Diamond, Bar Prongs, Prong Setting, Accent Stones, Engagement Ring", "Description": "This platinum engagement ring features a 3.11ct emerald cut diamond (D SI1) along with baguette accent diamonds, weighing .57ctw.", "Designer": "Robert Corio Designs", "Name": "", "Keywords": ""},
{"Type": "Engagement", "Images": "https://v5.airtableusercontent.com/v3/u/29/29/1718128800000/2opfUVRxs_hVn3dykOjDpA/QKt2c7N-FZVeXoG9yBPkCCcUzDvj_Ce8rAG6jCJ3qEtVMpSwaQM9rHyBjXFprAq0avUcUC_ROQ0LNofZS04kj4ytcw8UWEcV5up7AvPoolvIFZ4smfXozY2pe0nQtMg75-foE_SWUWhTKPD8QwshjTaqGJlGUDE6tn0u0qMuHGU/SxjEPJ7lznkCR8rQ9VDpCyuh3ULHUIfuERor1CgW46Q", "Materials": "Yellow Gold, Diamond, Channel Setting, Accent Stones, Hinge Ring, Bezel Setting, Tapered Band, Engagement Ring", "Description": "This yellow gold hinge ring features a .59ct diamond along with accent diamonds, set in a channel.", "Designer": "Robert Corio Designs", "Name": "", "Keywords": ""},
{"Type": "Engagement", "Images": "https://v5.airtableusercontent.com/v3/u/29/29/1718128800000/1USIM0c-NvQK4R3qlYpYjw/l0C24p7Kt02ZvRcecwmP-Nb7rYinmdS0kaUgVCB8cqxS7UxS83G5NppbMcf0-T2UjFI58hwqnk7QhC4vKLUH3tVIVhKjj6QsIma6yu71EtaMBvInSVQ3IfCXUlSWvRLlStFK0DZEHAKh_ygHp1-rRLv3jf-AIH5MeGkop5c9fKU/bQDjFtayIeB9onJNzJLD7D4d1yeaOt3WWq4-hOEkxKc", "Materials": "Yellow Gold, Diamond, Accent Stones, Shared Prongs, Platinum Setting, Prong Setting, Engagement Ring", "Description": "This yellow gold engagement ring features a .82ct round cut diamond and sixteen 1.8mm accent diamonds along the band.", "Designer": "Hegeman & Co.", "Name": "", "Keywords": ""},
{"Type": "Engagement", "Images": "https://v5.airtableusercontent.com/v3/u/29/29/1718128800000/0G00KUNduuJBMgGhgzptCg/xhlPiNKApBLDzqWD75HUvuHR5vRnW8poyFRO68_7BTmx29Lg7XChpuyR18A3kqvXJ4hJwWeL_yQ1B2KcLIuUwjs0Kec-AUpueA2fcpoZF8j5WpFSKegp0teeGEUJCQ1t9fmaCLx8PErfCaxfNATg4HOLqbTNDnWwhu9Kr2Rvh7c/3Pv-dV8QxOqlUVtZ3a6A7GPvJ3ACStFNpnUku9_JUu4", "Materials": "Platinum, Diamond, Cathedral Setting, Accent Stones, Prong Setting, Halo, Cutouts, Filigree, Engagement Ring", "Description": "This platinum, cathedral setting engagement ring features a round cut main diamond with a diamond halo, along with additional princess cut diamonds along the band.", "Designer": "Robert Corio Designs", "Name": "", "Keywords": ""},
{"Type": "Engagement Ring", "Images": "https://v5.airtableusercontent.com/v3/u/29/29/1718128800000/SEu7y5HdM-g3ez4qB-5UQg/xmsXnHyvnYA__cnccIpxAbAolkxRCi_UQ6wvHmxiGQfuCxdJpircRutrpe5xNHVsx-bOq1xqpHI7uoS7kvTOwRx7LSoDm52jsVblR8gXZBv8Pu_oS8CUvuPCGV_b2l8s9Xrn5upSxNy0ckxaltaAMYYYbw9s-DqJSu7uhCb80ok0CmVd8CyB8l4ygI03Bunr/ubO6WDwZkJ7BVwfGqfCWNnPC6r1jHFYfJnu43ZD2Rw0", "Materials": "Yellow Gold, Diamond, Half Moon Bezel, Twist, Solitaire", "Description": "This 18k yellow gold solitaire engagement ring features a twist shank and a 1.6ct round cut diamond, set with a half moon bezel.", "Designer": "", "Name": "", "Keywords": ""},
{"Type": "Engagement Ring", "Images": "https://v5.airtableusercontent.com/v3/u/29/29/1718128800000/RG9vH42ApfmYpPgD50CpyQ/5PWIEneuNLcIMNhDmWocC5ANhul2JA9TWGtolMJU7zRc39QZBycd1p9EZ645xt8zXW7gvL_jD7zv3dwuDzylvpndW_pAO4HHn6dpPHJNvCBwpa9leqR3haEaZrciICTYqYnkFKLp6u35Q_ulLTxdNg/jwBXg5Upsa9uAOVB42MVFZrwlSwxJsojkFS_K7qGlrY", "Materials": "Yellow Gold, Platinum, Solitaire, Diamond, Engagement Ring, Prong Set", "Description": "This 18k yellow gold solitaire ring features a round cut diamond, set with platinum prongs.", "Designer": "", "Name": "", "Keywords": ""},
{"Type": "Engagement Ring", "Images": "https://v5.airtableusercontent.com/v3/u/29/29/1718128800000/rbuDf7m3ErLROrVI7NbIGw/qDYhRH7geGwl8D1cx7e_KIpKwfVBsrcBmqyI4mdS8awInUKB5bYvQCrerbekh-_OBTjPKJAhLG3Cotes0w4JVb0QlfMl32nJEO0H0ynZRt-PWMTM7AKE0RasJpe4F-x4Aij8361KGbWi8s7ZSTWiNOPnQHUqxhUekorKihDiSmI/QeDCCtOvcTqGT_80inHT8KrQG2rLfrRyFxGlGKuUxQE", "Materials": "Platinum, Oval, Accent Stones, Diamond, Prong Setting", "Description": "This platinum ring features an oval cut diamond and round cut accent diamonds along the band.", "Designer": "", "Name": "", "Keywords": ""},
{"Type": "Engagement Ring", "Images": "https://v5.airtableusercontent.com/v3/u/29/29/1718128800000/Qc5b1cDSxsfSU02YXW0IeA/1N7i1v9JP_1BkAlVq8nS0uwmkagy1S2q6nkLFzhXG5B2NobglKl0_4F-DrqnxwINMyl-Q0xL7e8x2PcK3NNEVruR3JDf5pnOXfU6AgLENtYdDiJNvO_zkPmMI7KVzszR0KFK06SU0VyEsPnDORvqdg/74bY56hWfg-MDPdWz3l7jBwu-OvziQlITHQ83shRzf8", "Materials": "Platinum, Cathedral, Solitaire, Diamond, Engagement Ring, Prong Set", "Description": "This platinum cathedral ring features a round cut diamond, prong set.", "Designer": "", "Name": "", "Keywords": ""},
{"Type": "Engagement Ring", "Images": "https://v5.airtableusercontent.com/v3/u/29/29/1718128800000/q4ybU0lJhh99tsDhEnnr-Q/0hNqdo87WfBxhUDKLfa1RmNW35qJQy7yiYGdDQVxABIlCAyCGdhvrq3SiBOHrTLdQWcYnqTx7WAQoL_sOzObFj9j5cUEHI-o7f51mtbl65zm-lTNXoMEIY11ZDO9SeVvVaL3LpTJH7oEGxbyjIEn_Wkx9GShDHXbCT0PZBKa5sI/qHq1LlrRY2CovndIU0QtdMwJCwMaX4tIXzvmV1oiUgI", "Materials": "Platinum, Prong Set, Diamond, Accent Stones", "Description": "This platinum engagement ring features a round cut main diamond along with accent diamonds along the band.", "Designer": "", "Name": "", "Keywords": ""},
{"Type": "Engagement Ring", "Images": "https://v5.airtableusercontent.com/v3/u/29/29/1718128800000/q1yXqyMF048amJji5zY4ww/2WHvC_RUc7b3i7ZWu1dS6MiVjND4PC-FQWxYyctUDxftIFaziQK5M9kD4UI8iarrTEirvPY7QdRoZvZitsuyj-wftAntDmVskV85Xa6axVA91HheGQUBqyHmq4PyPGzbDUjetG6gJlGC635qbnY1GSGnH6asNKIz00yKdHV7IxM/sfykmATQxCEbCHKmIbbOya8IT-yR19r7g7nDdh1Kge0", "Materials": "Platinum, Princess Cut, Trillion, Diamond, 3 Stone, Prong Set", "Description": "This platinum ring features a princess cut diamond and two trillion cut diamonds, set with prongs.", "Designer": "", "Name": "", "Keywords": ""},
{"Type": "Engagement Ring", "Images": "https://v5.airtableusercontent.com/v3/u/29/29/1718128800000/odlSTv7egOWDbM6-aLZk5g/JY-N1qlf9o74WRk2rOsQh4TtMTRgWuncUHtnA2Ar6ivDjZemphV4qBlj7v9EpGs-h7HeUJfdZ9mxvqNIVmM1qeDlS9Hgw7IEv6KupfziXaZVOBOfoBGlVNkM7XyXfC97yyguUsOIFEiGZEWTQWKQag/SnHn5JoGInOgHBbIxDyYq3AKIyPnAPEEyRu42fioDv0", "Materials": "Platinum, Halo, Milgrain, Sapphires, Accent Stones, Diamond", "Description": "This platinum ring features a round cut diamond surrounded by a diamond halo, milgrain detail, and round cut sapphires along the band.", "Designer": "", "Name": "", "Keywords": ""},
{"Type": "Engagement Ring", "Images": "https://v5.airtableusercontent.com/v3/u/29/29/1718128800000/KNZ3Za60rGS4y7HPjfdhmA/Z3dN3iGgfpklB65qd-ZGlWxcJBMWas70difC8EWBCHARkDNmq7X6uRM_FUbTQB4hWLTlaXLBgC7PYBwawuu9yBfEupxqrsKI8XwNkKXFVpWyGUjFCf9dsoiHV64CEzoei9n3NHGv3gRjhzA3x6Z8Rg/RvZzzOyNYqRylZONQkdd19GGG1i54zP8cDFFEv-wnOs", "Materials": "Platinum, Pear, Diamond, Engagement Ring, Marquise, Hidden Stone, 3 Stone", "Description": "This platinum ring features a pear cut main diamond and two marquise cut diamonds. This ring also features a round cut hidden diamond along the band.", "Designer": "", "Name": "", "Keywords": ""},
{"Type": "Engagement Ring", "Images": "https://v5.airtableusercontent.com/v3/u/29/29/1718128800000/JsQNQHCtDqYfcVVMK27ZXA/QGgVAg0Bu-zxAdJ6xm5-cgXmpTyLGmsB8yXPna_WEsRwHO2-DZSnuN3ahpnw4LA66TebUdty68H8eiiAdLP8znkykFeE3Ki33TBDQnguemNjY8Iz2YHyN7evTCqCv8c-wQFWdjRdcwHi4pI0_ZBxnA/JjquLh85mveByquY4w4Xda0b05TBayD_E86kQneEMFw", "Materials": "Rose Gold Band, Platinum, Half Moon Bezel, Cushion Diamond", "Description": "This 18k rose gold ring features a cushion cut diamond, set in a platinum half-moon bezel.", "Designer": "", "Name": "", "Keywords": ""},
{"Type": "Engagement Ring", "Images": "https://v5.airtableusercontent.com/v3/u/29/29/1718128800000/HQAQWHy9h3HDuALEtsa0aw/c4QUD2FqC23h1P6N8UsrlP9KwIUV1wvnY3AGMbN40pNfx0a3D7ox_TGRdvkXvJxlKh9oVL9CuZnRVSXTGDNNHYhOMMxK8cMbKAA_uZ-0s0SfnvorpqONBptvRZq4Jqmsmek-mFgd8IMaF5h4PFpd0jSh3g6dcDxoCQTqUSsbmiM/ekYwjzZhmCKvp6jiWet0mOwixTddegvm5SoaMtbFCBA", "Materials": "Platinum, Diamond, Pink Diamond, Accent Stones, Prong Setting, Half Moon Bezel Set, European Shank, Channel", "Description": "This platinum engagement ring features round cut white and pink diamonds, set with half moon bezels and prongs. This ring also features a European shank.", "Designer": "", "Name": "", "Keywords": ""},
{"Type": "Engagement Ring", "Images": "https://v5.airtableusercontent.com/v3/u/29/29/1718128800000/GJ72BLuFnLEuQmzTxygb4g/vviPoUegVHEXIHwtE9RP0G3s6_RIkcVmQTFkh4foK9Gr99fLbL9khQrET9Q2V5PUHlTDCXAT3fTWn0RjGvJ7-y94m_mCciJrcczYj0PZfCJ1y8aeJOGdCEX398hK8hML_MMXvoN00EbS8FhjaDVMd753-MauDoaGY-KppJgDg1E/Dgwa4aPAkiIEquR4DACr1X79nBtHWomYHKG3iQF2D9g", "Materials": "Platinum, Diamonds, Pink Diamonds, Engagement Ring, Half Moon Bezel Set, Prong Setting", "Description": "This platinum ring features round cut diamonds and pink diamonds, some half-moon bezel set and some prong set.", "Designer": "", "Name": "", "Keywords": ""},
{"Type": "Engagement Ring", "Images": "https://v5.airtableusercontent.com/v3/u/29/29/1718128800000/dub5eij4WYC4VP4BAJxkSA/ziiXPtMdVUAZPA9ijglKHJXaI4m427QFeeXz1UZaUpMF9OTva7-PLlhjUgQnU7OTwPTiO1CT9T-Pzyhgn9MVPJ-d8gZjNKZo86JkKgGtXWpqujlDnkLXNQLUGaIK0daMoDxB7U9bzIbtavfVXEjCIwNK5og1fIvWLClCYCZkVj8/fC7HIR7ejqBhvSNMK1LpR3sIuC0YN8aaRiIBPK4VYNE", "Materials": "Platinum, 3 Stone, Radiant, Trillion, Prong Setting", "Description": "This platinum ring features a radiant cut diamond and two trillion cut diamonds, prong set.", "Designer": "", "Name": "", "Keywords": ""},
{"Type": "Engagement Ring", "Images": "https://v5.airtableusercontent.com/v3/u/29/29/1718128800000/as5hAaMDtn8CBaRCnKDlRg/5rHOpKzxqprMp8Ke58OGtg_OujhuIWg93cGpC-LFWUMyEf0CwTnDLxRcPlBTdZ5KzffqzRsLiGGmdVhTUBOfS3YuI56GYlb6xuM98D6jV7XQq3qea5qJjg1doj1v5wsmVgjN43id-11nKeXJsOhHKiHP-__fuTQWQbxSzQ1SU5M/9oBaO75zkm7Te1GsHseH6g-UUventvw1F6BcdBv2j3U", "Materials": "Platinum, Yellow Gold, Oval Diamond, Prong Set, Tapered", "Description": "This 18k yellow gold solitaire ring features an oval cut diamond.", "Designer": "", "Name": "", "Keywords": ""},
{"Type": "Engagement Ring", "Images": "https://v5.airtableusercontent.com/v3/u/29/29/1718128800000/_ARySQT_wsRfGxIUv0_lBQ/Ar8c3b0q50CtXDIv3RFhZCBuHCyoPkY2o7-MxBXHeU4h80HZqkQ7KZ1vYluDe-5BlgAyyjdMVDafA6jvR2Yp5PdPrsVBGZPAQwziJsHpdIAZXjIbGAH3U6j3t97tlA9Kfjfxdp4Uinr4PieDXbkoLWSMxrYCiUq2miB-vBFkq18/JutSpMfoOFma-fOeqJjjHFFn8i-4akkkadY8dUluog4", "Materials": "Yellow Gold, Platinum, Diamond, Solitaire, Prong Setting, Peek-A-Boo, Hidden Stone", "Description": "This is a 18k yellow gold solitaire diamond ring, set with platinum prongs, featuring a peek-a-boo diamond.", "Designer": "", "Name": "", "Keywords": ""},
{"Type": "Engagement Ring", "Images": "https://v5.airtableusercontent.com/v3/u/29/29/1718128800000/5wSCIqdhotZx3Eab0IDNdw/mdyXjx08HY3jDrHW7wiIWTMwzmSzLgJ1IDC7fcidJHUoA610n-WmLlD8z_lmYW9r1I97_kLG6r5GCH-M5mfkk15YMgjeBUwCxQMdyE2fdPhK4E747HAZAySUJq66tuPmWW0uOEpXahMUNaAY4FGedg/xmjiFBAT1TSwklrdlmc-QiaSiqzH03QlbNq4lanT5LM", "Materials": "Platinum, Yellow Gold, Prong Setting, 3 Stone, Diamond, Emerald", "Description": "This platinum ring features a round cut emerald, set in 18k yellow gold, and two round cut diamonds set in platinum.", "Designer": "", "Name": "", "Keywords": ""},
{"Type": "Engagement Ring", "Images": "https://v5.airtableusercontent.com/v3/u/29/29/1718128800000/4f0tjg8IdUjp0Y7o4UVDvA/69pOUYRelofbZ_Gxigb-mmMqWLuIqB8tt8otGvY6vrmkABL0AmMHfsp-6anmxx9ormGd03Kxnusv72CPh5Qw88KzFAdo3_YSZUs3i8KGJi7GZAkrhNOW7J2N3rt1CHJ2dGfeEybuqW_MfqonoY7aSo0I9M61JZ-APUNytkgsoaY/4DxYbxH_hI7HEhLwbYKI2qF8OCa1pH6mPLP2YjkVfs0", "Materials": "Platinum, Sapphire, Diamond, Engagement Ring, Accent Stones", "Description": "This platinum engagement ring features a round cut main diamond along with round cut accent diamonds and sapphires along the band.", "Designer": "", "Name": "", "Keywords": ""},
{"Type": "Engagement Ring", "Images": "https://v5.airtableusercontent.com/v3/u/29/29/1718128800000/3bt29XEm__rXntncIsT0FA/95vLZ9pqnS_16lE7KMrshk5Td8-JWxMBESTa_zd_B7fhNEGdB5vT2C3bsZo0nGYaZPBE9KIGWjXWN6NCPT_LNuUODpzqNbqG3W2v-wUPDs6oombI95wWjtlWvBUwvxXXzci5ZUcaXAWJwJSTZlIEaHQLoM3ruiR_jkzbymCma48/Omv7ewkTNgixLcsvDsVrli4V709OISMeVno_4W22Jqs", "Materials": "Platinum, Yellow Gold, Diamond, Prong Setting, 3 Stone, Radiant", "Description": "This platinum ring features radiant cut diamonds, prong set.", "Designer": "", "Name": "", "Keywords": ""},
{"Type": "Engagement Ring", "Images": "https://v5.airtableusercontent.com/v3/u/29/29/1718128800000/2w6b6iQPRRKnz50CouJA3w/-ApVj90YMIlXz6t1EQlCr9R77UtW253GzkSy7mNQUTpn5Ta4wcOtCVxjdmfEBotxA9NRhgPwQrH-FB9hXrR2wgck0G7IldQgF_-gyUOiSoTeXVFPZEOuPwVNiQFL4jRclY3boYncit5thQS_vW2f8kJvbDamNXRywlCeaddWNvI/rgPGvQxcByoK5a_i1eCqPWh_ukipBmKWmPw7L4xaB5s", "Materials": "Platinum, Cathedral, 3 Stone Setting, Engagement Ring, Diamond, Tapered", "Description": "This platinum cathedral ring features three round cut diamonds, set with prongs, on a tapered band.", "Designer": "", "Name": "", "Keywords": ""},

        // Add more items from the CSV data here
    ];

function renderGallery(data) {
        const gallery = document.getElementById("gallery");
        gallery.innerHTML = '';

        if (data.length === 0) {
            const noResultsMessage = document.createElement("p");
            noResultsMessage.innerHTML = "We will design it for you!<br>It looks like we could not find a ring to those specifications in our database, so we will send you a rendering.";
            noResultsMessage.classList.add("no-results");
            gallery.appendChild(noResultsMessage);
            return;
        }

        data.forEach(item => {
            const galleryItem = document.createElement("div");
            galleryItem.classList.add("gallery-item");
            galleryItem.innerHTML = `
                <img src="${item.Images}" alt="${item.Description}">
                <h2>${item.Designer}</h2>
                <p class="materials">${item.Materials}</p>
                <p>${item.Description}</p>
            `;
            galleryItem.addEventListener("click", () => openModal(item));
            gallery.appendChild(galleryItem);
        });
    }

    function filterGallery(event) {
        const query = event.target.value.toLowerCase().trim();
        let filteredData = [];

        if (query.includes(',')) {
            const terms = query.split(',').map(term => term.trim());
            filteredData = galleryData.filter(item => {
                return terms.some(term =>
                    item.Description.toLowerCase().includes(term) ||
                    item.Materials.toLowerCase().includes(term) ||
                    item.Designer.toLowerCase().includes(term)
                );
            });
        } else {
            const terms = query.split(' ').map(term => term.trim());
            filteredData = galleryData.filter(item => {
                return terms.every(term =>
                    item.Description.toLowerCase().includes(term) ||
                    item.Materials.toLowerCase().includes(term) ||
                    item.Designer.toLowerCase().includes(term)
                );
            });
        }

        renderGallery(filteredData);
    }

    function openModal(item) {
        const modal = document.getElementById("modal");
        const modalImage = document.getElementById("modalImage");
        const modalDesigner = document.getElementById("modalDesigner");
        const modalMaterials = document.getElementById("modalMaterials");
        const modalDescription = document.getElementById("modalDescription");
        const secondaryImages = document.getElementById("secondaryImages");

        modalImage.src = item.Images;



        secondaryImages.innerHTML = '';
        const originalImage = document.createElement("img");
        originalImage.src = item.Images;
        originalImage.alt = item.Description;
        originalImage.addEventListener("click", () => {
            modalImage.src = item.Images;
        });
        secondaryImages.appendChild(originalImage);

        if (item.SecondaryImages && item.SecondaryImages.length > 0) {
            item.SecondaryImages.forEach(imgUrl => {
                const imgElement = document.createElement("img");
                imgElement.src = imgUrl;
                imgElement.alt = item.Description;
                imgElement.addEventListener("click", () => {
                    modalImage.src = imgUrl;
                });
                secondaryImages.appendChild(imgElement);
            });
        }

        modal.style.display = "block";
    }

    function closeModal() {
        const modal = document.getElementById("modal");
        modal.style.display = "none";
    }

    document.getElementById("searchBar").addEventListener("input", filterGallery);
    document.querySelector(".close").addEventListener("click", closeModal);
    window.addEventListener("click", (event) => {
        const modal = document.getElementById("modal");
        if (event.target === modal) {
            modal.style.display = "none";
        }
    });

    // Initial render
    renderGallery(galleryData);
});